### DISCUSSION TITLE
How do you host an 11ty site on GitHub pages?

### DISCUSSION THREAD

**Discussion by binyamin** [11ty/eleventy#1455] [Q&A] [answered]
Jekyll works very well with GitHub pages. So does React. But Eleventy poses some difficulties.

I'm sure this question has been answered umpteen times, and asked twice as often. I'm interested in what different solutions people use.

**Comment by Ryuno-Ki** [comment]
I'm not hosting on GitHub myself (bot on the Shared Hosting provider called Uberspace), but hosting on GitHub would imply a `gh-pages` branch on the repo. The URL is build as [`https://<username>.github.io/<reponame>/`](https://pages.github.com/). You can even create one without `<reponame>` if the repo is called like the domain.

Lastly, using the npm package [gh-pages](https://www.npmjs.com/package/gh-pages) can be pointed to the output directory by eleventy as a `postbuild` step (for example).

**Reply by binyamin** [reply]
>but hosting on GitHub would imply a gh-pages branch on the repo

Not necessarily; iirc Jekyll and React work automatically.

**Reply by Ryuno-Ki** [reply]
Well, there are a [few different steps necessary](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/setting-up-a-github-pages-site-with-jekyll) but it works almost the same.

Keep in mind, that there is a [limitation](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll) on the [themes you can use](https://pages.github.com/themes/) (for security reasons).

As far as I know, GitHub was built with Ruby (on Rails) in the beginning. Thus, Jekyll is close enough to be offered as a service.

Can't tell about React support.

**Comment by nhoizey** [comment, marked as answer]
There's a tutorial written by @lea37 here: https://lea-tortay.com/writings/github-pages-eleventy/index.html

**Reply by TigersWay** [reply]
Does not work anymore ... At least, as of today! @lea37

**Reply by lea37** [reply]
Hi @TigersWay i am rebuilding my website but you can have access to this post here 
https://www.linkedin.com/pulse/eleventy-github-pages-lea-tortay/
hope it help ! ;)

**Reply by edthedev** [reply]
Thanks @lea37 for the tutorial! I've been using this method for some time with 11ty, and it works great!

**Reply by architchandra** [reply]
Thanks for this. The article from @lea37 and https://www.rockyourcode.com/how-to-deploy-eleventy-to-github-pages-with-github-actions/ helped me.

**Reply by holdenmad** [reply]
Can someone explain why the `docs` solution works/worked?

**Reply by lea37** [reply]
> Can someone explain why the `docs` solution works/worked? 

It comes from GitHub itself
[See the doc here](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) 
> the source folder can either be the root of the repository (/) on the source branch or a /docs folder on the source branch

**Reply by holdenmad** [reply]
@lea37 Thank you so much 🙏🏼

**Comment by timkley** [comment]
This is also a great tutorial, written by [Sophia Brandt](https://twitter.com/hisophiabrandt): [https://www.rockyourcode.com/how-to-deploy-eleventy-to-github-pages-with-github-actions/](https://www.rockyourcode.com/how-to-deploy-eleventy-to-github-pages-with-github-actions/)

I used it to setup deployment for a page today in about 20 minutes, very well written!

**Comment by phineas-pta** [comment]
now github has it own action to deploy page, here an updated pipeline
```yaml
name: build 11ty site

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies & build
        run: |
          npm install
          npx @11ty/eleventy
      - uses: actions/upload-pages-artifact@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
```
just make sure the output dir is `_site`
