### DISCUSSION TITLE
Nested navigation using eleventy-navigation plugin

### DISCUSSION THREAD

**Discussion by jamesgrubb** [11ty/eleventy#1480] [Q&A]
Hello. My data is creating a number of paginated posts posts. My front matter is as follows:
```
---
pagination:
    data: cms
    size: 1
    alias: article
    addAllPagesToCollections: true
layout: "_base.njk"
tags: articles
permalink: "/articles/{{ article.title | slug }}/"
eleventyComputed:
    title: "{{ article.title }}" 
    eleventyNavigation:
        key: "{{ article.title}}"
        parent: "{{articles}}" //<-- how do I set the parent?
---
```
I would like my nav HTML structure to read

```
<ul>
  <li>articles</li>
    <ul>
     <li>post-1</li>
     <li>post-2</li>
    </ul>
</ul>

Thanks in advance.
