### DISCUSSION TITLE
Is there anyway to import data from multiple data files?

### DISCUSSION THREAD

**Discussion by pontakornth** [11ty/eleventy#1571] [Q&A]
I am trying to rewrite an even website that store events in similar format but in different files. It's actually TOML but for simplicity I will use YAML as example

```yml
name: "JavaScript Party"
parties:
   - "Random Fried Chicken"
   - "Mash up steak"
```

These events are stored in serperate files to prevent conflict as they're decentralized. I want to import them as one collection so I can use this.

```nunjuck
{%- for event in events -%}
   {{ event.name }}
   <!-- Insert more data here -->
{%- endfor -%}
```

Thank you in advance.
