### DISCUSSION TITLE
.html file is entirely YAML front matter, should be .yml?

### DISCUSSION THREAD

**Discussion by davetapley** [11ty/eleventy#1895] [Q&A] [answered]
I have a `_includes/cameras.html` which looks like this:

```html
<html lang="en">
  <head>
    <title>{{ title }}</title>
...

    {% for camera in cameras %}
...
          <div class="title">{{ camera.name }}</div>
          <a href="{{ camera.url }}" target="_new">
...
```

And it works great to generate from a collection of other `.html` like this:

```yml
---
layout: cameras
title: City Dam Conditions
cameras:
  - name: Camera One
    url: img_5efb570d3e69b200189830af.jpg
---
```

--- 

Since all these `.html` files ⬆️ are _just YAML_ I was rather hoping I could lose the `---` and rename them to `.yml`, but then no files are generated. That makes sense since YAML [isn't listed under Template Languages](https://www.11ty.dev/docs/languages/), but left me wondering: Am I doing something weird or wrong?
