### DISCUSSION TITLE
Running 11ty locally with Netlify CLI

### DISCUSSION THREAD

**Discussion by freshyill** [11ty/eleventy#1965] [Q&A] [answered]
I think this is a best practices question.

I'm trying to figure out which command I should be running with Netlify CLI. Netlify recommends [`eleventy --serve`](https://docs.netlify.com/configure-builds/common-configurations/eleventy/), but that already fires up Browsersync, which means I now have servers running on 8080 and 8888. 

The docs also recommend using 8080, but that conflicts with Browsersync. Is the solution here just as simple as ignoring the server running on 8888?

package.json:

```json
  "scripts": {
    "start": "netlify dev",
    "build": "NODE_ENV=production eleventy",
    "dev": "FORCE_COLOR=true eleventy --serve"
  },
```

netlify.toml:

```toml
[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  # port = 8080
```
