### DISCUSSION TITLE
Yaml multi line array to json for use in html

### DISCUSSION THREAD

**Discussion by madsem** [11ty/eleventy#2215] [Q&A] [answered]
I'm trying to get 11ty to just spit out the entire array of a multi-line frontmatter array, then use a custom filter to return a json stringified JS object for use in my html.

I'm sure I'm doing something silly and that this isn't a bug.

My frontmatter: (yaml)
```yaml
content_types:
  - type: button_grid
    title: Cool Buttons
    buttons:
      - button_class: button-green
        button_cta: Yes
        link:
          - 95c2cca9-b086-4e36-bda3-50096fb95711
          - d6b571fe-e50e-43d1-ad13-36c02cdf7fcf
      - button_class: button-red
        ...
```

usage inside a loop:
```html
{{ button.link | toJson }}
```

My filter:
```js
// array to json object for usage in html
  config.addFilter("toJson", (arr) => {
    console.log('this: '+arr)
    return JSON.stringify(arr);
  });
```

I expected that `arr` would be an array and filter return the stringified string, but what is logged in the filter is just a single string...

expected result:  
```json
{"95c2cca9-b086-4e36-bda3-50096fb95711","d6b571fe-e50e-43d1-ad13-36c02cdf7fcf"}
```

Given result:  
```95c2cca9-b086-4e36-bda3-50096fb95711```
