### DISCUSSION TITLE
Setting up CSS pipeline with addExtension and PostCSS plugins

### DISCUSSION THREAD

**Discussion by pepelsbey** [11ty/eleventy#2388] [Q&A] [answered]
There’s a great [example in the docs](https://www.11ty.dev/docs/languages/custom/#using-inputpath) how to build Sass styles using Eleventy’s own watcher. I tried to recreate it using plain CSS with some PostCSS plugins to combine imports, prefix and minimize it.

The full code is available here: [pepelsbey/11ty-postcss](https://github.com/pepelsbey/11ty-postcss).
I’m using the latest Eleventy canary v2.0.0-canary.11

```js
const postcss = require('postcss');
const autoprefixer = require('autoprefixer');
const csso = require('postcss-csso');
const pimport = require('postcss-import');

config.addTemplateFormats('css');

config.addExtension('css', {
  outputFileExtension: 'css',
  compile: async (inputContent, inputPath) => {
    let output = await postcss([
      pimport,
      autoprefixer,
      csso
    ]).process(inputContent, { from: inputPath });

    return async () => {
      return output.css;
    }
  }
});
```

I have the following structure:

```css
/* src/styles/index.css */
@import url('blocks/one.css');
@import url('blocks/two.css');

/* src/styles/blocks/one.css */
.one {
  color: tomato;
}

/* src/styles/blocks/two.css */
.two {
  color: plum;
}
```

And it works totally fine after `npm start`: I get `dist/styles/index.css` with the following:

```css
.one{color:tomato}.two{color:plum}
```

Unfortunately, it doesn’t work the way I expect during development.

If I change anything in the blocks, I get the event in the console:

```
[11ty] File changed: src/styles/blocks/one.css
[11ty] Copied 14 files / Wrote 11 files in 0.05 seconds (4.5ms each, v2.0.0-canary.11)
```

But I don’t get updates in the resulted `dist/styles/index.css` and in the browser. Only when I change `src/styles/index.css` I see changes in the browser and in the `dist` folder. Also, when I change `.eleventy.js` it also does the full rebuild.

Any idea how to make it work? It would make a such an elegant CSS build pipeline!
