### DISCUSSION TITLE
Accessing pagination data in the front matter

### DISCUSSION THREAD

**Discussion by danielLee0721** [11ty/eleventy#2580] [Q&A] [answered]
I currently have the following setup:

default.html (my main layout file)
`  <title>{%- if title -%} {{ title }} {%- else -%} {{ site.title }}{%- endif -%}</title>`

gallery-breast-augmentation.html (using pagination)
```
---
layout: default.html
pagination:
  data: dynamic.gallery.breast-augmentation
  size: 1
permalink: "gallery/breast/breast-augmentation/{{ pagination.pageNumber | plus: 1 }}/"
title: Check out this before & after result of our breast augmentation patient  #{{ page.pageNumber | plus: 1 }}
---
```
Doing this generates pages with the following permalinks
gallery/breast/breast-augmentation/1/
gallery/breast/breast-augmentation/2/
gallery/breast/breast-augmentation/3/
etc

But, the same thing doesn't happen to the <title>
The title ends up being just "Check out this before & after result of our breast augmentation patient"

I would like the title to output the following
"Check out this before & after result of our breast augmentation patient #1"
"Check out this before & after result of our breast augmentation patient #2"
"Check out this before & after result of our breast augmentation patient #3"
etc

When I do just
`title: {{ pagination.pageNumber | plus: 1 }}`
to troubleshoot, I get the following
<title>{"[object Object]":null}</title>

Any ideas?

Thank you.
