### DISCUSSION TITLE
Pagination size index

### DISCUSSION THREAD

**Discussion by danielLee0721** [11ty/eleventy#2581] [Q&A] [answered]
Hi everyone,

If I have the following pagination setup
```
pagination:
  data: dynamic.gallery.smile-makeover
  size: 12 
permalink: "gallery/cosmetic-dentistry/smile-makeover/{{ pagination.pageNumber | plus: 1 }}/"

```
is it possible to access some sort of index number for my items so that
on page gallery/cosmetic-dentistry/smile-makeover/1
items have index from 1 to 12
and on the following page gallery/cosmetic-dentistry/smile-makeover/2
items have index from 13-24

The reason why I am trying to do this is because I am using the above pagination for displaying all the before & after results (12 per page with navigation at the bottom) and another pagination for generating individual pages with one result per page
gallery/cosmetic-dentistry/smile-makeover/patient/1
gallery/cosmetic-dentistry/smile-makeover/patient/2
.
.
.
gallery/cosmetic-dentistry/smile-makeover/patient/23
gallery/cosmetic-dentistry/smile-makeover/patient/24
etc

Any advice would be greatly appreciated.

Thank you! 🙏🏼
