### DISCUSSION TITLE
Can I programmatically compose tags as front-matter?

### DISCUSSION THREAD

**Discussion by ed-ponce** [11ty/eleventy#2632] [Q&A] [answered]
I want to create collections for every pagination page based on the pagination template `fileSlug`. For that, I’m setting a tag based on the template’s file name as front-matter defaults through the directory data file, like so:

```
/src
  └─ /collections
      ├─ collections.json
      └─ articles.liquid
```

```json
// collections.json
{
  "eleventyComputed": {
    "tags": "{{ page.fileSlug }}"
  }
}
```

```yml
// articles.liquid
---
pagination:
  alias: article
  data: shop.articles
  size: 1
  addAllPagesToCollections: true
eleventyComputed:
  title: "{{ article.title }}"
permalink: "/{{ page.fileSlug }}/{{ article.id }}/"
---
```

**The `page.fileSlug` variable won’t render anything** when put in the directory data front-matter defaults context. A problem not present for the template’s front-matter; `title` and `permalink` compute properly.
