### DISCUSSION TITLE
How would you include arbitrary markdown files, in some other directory, as part of the input for eleventy?

### DISCUSSION THREAD

**Discussion by mendhak** [11ty/eleventy#2648] [Q&A] [answered]
I've got my `.eleventy.js`, my markdown files with some content in it, my layout html in one directory.  Eleventy works just fine and generates the content I need.  

Now suppose there's a few additional `.md` files that are in a different directory that I want to include as part of the HTML generation.  Let's say it's at `../../common/123.md` and for various reasons they have to stay in that location.  

How would you approach this? Is there a way in eleventy to include specific, arbitrary files as part of the 'input'?  

Or would you set up a build step in package.json that copies those specific files over first before eleventy runs?  

Something else?

**Comment by pdehaan** [comment]
If the "../../common/123.md" file is outside of the input folder, I've seen some people use [symlinks](https://www.switchingtomac.com/tutorials/osx/how-to-create-symlinks-on-your-mac/) in the past.
But I haven't experimented with that recently to see how useful it is versus copying the assets into the project.

**Comment by mendhak** [comment, marked as answer]
Hey thanks for the answer. The approach I ended up going with, was via docker-compose, volume mounts.  

```yaml
version: "3"
services:
  eleventy:
    image: node:16-slim
    volumes:
      - ${PWD}:/app
      - ${PWD}/../common:/app/common
      - ${PWD}/../../specific.md:/app/text/specific.md
    working_dir: /app
    environment:
      - DEBUG=Eleventy*
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npx eleventy --watch --serve
    ports:
      - 8080:8080

```
It does work, the --watch and --serve is doing fine, but does have some minor quirks I can live with.  Namely - Ctrl + C takes a while to 'kill' the application, it's fine.
