### DISCUSSION TITLE
Adding tags to pages created from paginating a data set

### DISCUSSION THREAD

**Discussion by danielLee0721** [11ty/eleventy#2748] [Q&A] [answered]
Hi Everyone,

When creating a bunch of pages by using the pagination feature and iterating over a data set, is it possible to add tags to them somehow?

What I am trying to do is query a headless CMS for all my blog posts and then utilize pagination to generate individual blog pages. Unfortunately, I am not able to add `tags` to `eleventyComputed` to create collections...

Any help would be greatly appreciated.

Thank you! 🙏🏼

```
---
layout: defaultPage.html
pagination:
  data: blogPosts
  size: 1
  addAllPagesToCollections: true
permalink: "/blog/{{ pagination.items[0].title | slug }}/"
eleventyComputed:
  title: "{{ pagination.items[0].title }}"
  description: "{{ pagination.items[0].content | truncatewords: 20 | strip_html }}"
---
```
