### DISCUSSION TITLE
Is it possible to set the pagination.size value from a global data file?

### DISCUSSION THREAD

**Discussion by mendhak** [11ty/eleventy#2765] [Q&A] [answered]
Is it somehow possible to set the pagination.size value from a global data file?

I've got a `metadata.json` file in which I've put the value:

```json
{
...
"paginationSize" : 9,
...
}
```

Now in my layout's frontmatter, which is paging over a collection, it would be nice if I could read the pagination size from metadata.json

```
---
title: All posts
layout: layouts/home.njk
pagination:
  data: collections.posts
  size: {{ metadata.paginationSize }}
  alias: postslist
  reverse: true

permalink: /posts/{% if pagination.pageNumber > 0 %}{{ pagination.pageNumber }}/{% endif %}
---

```

Of course this isn't working.  Could this be done via an eleventyComputed instead? I didn't know what to put in there.
