### DISCUSSION TITLE
Dynamic image in header

### DISCUSSION THREAD

**Discussion by GitOffMyCode** [11ty/eleventy#2784] [Q&A]
Hello, new to Eleventy and just wondering why something isn't work as expected...

I am making a simple site with 4 pages. 
I want an image in the header to change depending on which page the user is on.

I have a typical set up with a base file which includes a header.

On each of my html pages I have front matter which specifies which image and alt text to show:

```
headerImage: peace-sign.svg
headerAlt: A hand making a peace sign

```

Then in my header I am pulling that in:

`src="assets/images/{{ headerImage }}`

**It works on index.html but not on any of the other pages, I get no image just "NaN"**

I'm stumped!

**Comment by GitOffMyCode** [comment]
It may be worth adding that I'm using Eleventy navigation

```
layout: layouts/base.html
headerImage: peace-sign.svg
headerAlt: A hand making a peace sign
eleventyNavigation:
  key: About
  order: 1
```
