### DISCUSSION TITLE
Having trouble when creating  anew collection

### DISCUSSION THREAD

**Discussion by cat-a-flame** [11ty/eleventy#2865] [Q&A]
Hi there lovely people!
I want to build my blog by using eleventy, and, so far, everything works as expected, only one thing I can't get my head around: I wanted to create a collection named Category. Each post will have their own, similar to tags, but there is only one category per post. Since they are the same, I've copied the tags collection, and everything works, except the single category page, the categories list is fine. I can't figure out why, I don't have errors, only a 404 page when I click the category to see what other posts in there.

eleventy.config.js
```
eleventyConfig.addFilter("getAllCategories", collection => {
    let categorySet = new Set();
    for(let item of collection) {
        (item.data.categories || []).forEach(category => categorySet.add(category));
    }
    return Array.from(categorySet);
});

eleventyConfig.addFilter("filterCategoryList", function filterCategoryList(categories) {
    return (categories || []).filter(category => ["all", "nav", "post", "posts"].indexOf(category) === -1);
});
```

categories-list.njk
```
---
permalink: /categories/
layout: layouts/home.njk
---
<h1>Categories</h1>

<ul>
{% for category in collections.all | getAllCategories | filterCategoryList %}
    {% set categoryUrl %}/categories/{{ category | slugify }}/{% endset %}
        <li><a href="{{ categoryUrl }}" class="post-tag">{{ category }}</a></li>
    {% endfor %}
</ul>
```

categories.njk:
```
---
pagination:
  data: collections
  size: 1
  alias: category
  filter:
    - all
    - post
    - posts
    - categoryList
  addAllPagesToCollections: true
layout: layouts/home.njk
eleventyComputed:
  title: Tagged “{{ category }}”
permalink: /categories/{{ category | slugify }}/
---
<h1>Tagged “{{ category }}”</h1>

{% set postslist = collections[ category ] %}
{% include "postslist.njk" %}

<p>See <a href="/categories/">all tags</a>.</p>
```

blog.11tydata.js
```
module.exports = {
    tags: [
        "posts"
    ],
    categories: [
        "posts"
    ],
    "layout": "layouts/post.njk",
};
```
