### DISCUSSION TITLE
How to use function exported from JS directory data file for pagination

### DISCUSSION THREAD

**Discussion by dave-kennedy** [11ty/eleventy#2917] [Q&A]
This is my content directory:

```
content/
├── links/
│   ├── index.json
│   ├── index.md
│   ├── tags.11tydata.js
│   └── tags.md
└── index.md
```

tags.11tydata.js:

```
module.exports = {
  linksByTag: function () {
    return [{
      tag: 'Podcast',
      tagSlug: 'podcast',
      posts: [{
        "page": {
          "date": "2023-03-13T12:35:02-0600",
          "url": "https://www.thisamericanlife.org/639/in-dog-we-trust"
        },
        "data": {
          "tags": ["Podcast"],
          "title": "This American Life Ep. 639: In Dog We Trust"
        }
      }],
      pageNumber: 0,
      totalPages: 1,
      currentHref: '/links/tags/podcast',
      nextHref: null,
      previousHref: null,
    }];
  }
};
```

tags.md:

```
---
eleventyComputed:
    title: "Links tagged with {{ tagPage.tag }}"
layout: tags.liquid
pagination:
    data: linksByTag
    size: 1
    alias: tagPage
permalink: "{{ tagPage.currentHref }}/"
---
```

Throws this error:

```
[11ty] Unexpected data found in pagination target (./content/links/tags.md): expected an Array or an Object. (via Error)
```

Changing this part of the template:

```
pagination:
    data: linksByTag()
```

Throws another error:

```
Could not find pagination data (./content/links/tags.md), went looking for: linksByTag() (via Error)
```

But if I change `linksByTag` from a function to an array, and remove the parens after `linksByTag` in the front matter, it works.

Is it possible to call a function exported from a JS directory data file in this way?
