### DISCUSSION TITLE
paging more than one collection

### DISCUSSION THREAD

**Discussion by bsastregx** [11ty/eleventy#2937] [Q&A]
So far I think I understand pagination.
Is it possible to add more than one collection to a pagination?
Let's say I want to include all 'posts' with tag 'technology' and 'food' at the same time:

```
---
eleventyNavigation:
  key: Home
  order: 1
pagination:
  data: ['collections.technology', 'collections.food']
  size: 3
  alias: posts
  reverse: true
  generatePageOnEmptyData: true
---
```
