### DISCUSSION TITLE
Adding pagination to home index page stops only that page from re-generating

### DISCUSSION THREAD

**Discussion by ng-chicago** [11ty/eleventy#3084] [Uncategorized]
When I add pagination to the front matter of my main index.html, ONLY the home page stops getting built 
There are no errors and changes to other files are built just fine (running dev)

What simple thing am I missing?
Trying to learn 11ty

"@11ty/eleventy": "^2.0.1",

Removing this makes it work again
```
pagination:
  data: collections.post
  size: 2
  alias: posts
```
