### DISCUSSION TITLE
How can I set a default layout and permalink for a collection?

### DISCUSSION THREAD

**Discussion by drakonicguy** [11ty/eleventy#3166] [Q&A] [answered]
Hi,

Apologies if this is similar to a discussion that's already been posted here. Please point me in the right direction if this has been answered somewhere. I don't really know how to search for this.

I'm trying to move my site to 11ty from Jekyll, and I'm having trouble finding out if defaults can be set for a collection.
In my Jekyll `_config.yaml`, I have:
```
collections:
  posts:
    permalink: /blog/:year-:month-:day-:title:output_ext
```
and
```
defaults:
  -
    scope:
      path: ""
      type: "posts" 
    values:
      layout: "blog-main"
```
which sets the default layout for posts to `blog-main`, and their paths to `/blog/year-month-day-title.html`. How can I recreate this in 11ty?
