### DISCUSSION TITLE
Adding a widget that will automatically generate URL when new post is created

### DISCUSSION THREAD

**Discussion by mohammedasker** [11ty/eleventy#3259] [Q&A]
Hello. I originally asked this question on [Decap CMS](https://github.com/decaporg/decap-cms/issues/7185), however, no one seems to respond to it. So I'm hoping anyone with more knowledge can help me out figuring the problem.  

Alright, so I have a job board website that is built with Eleventy (11ty) and Decap CMS. I want to add a widget that will automatically generate the URL of posts I created from Decap CMS. The reason why I want it is so that every time I create new job posts, it will automatically add a URL in the markdown front matter. I need these URLs so that they will show up in Google Rich Results and improve the SEO of my website.

```yml

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blogs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Body", name: "body", widget: "markdown" }
    - { label: "Post URL", name: "posturl", widget: "slug" } <--- something like that

```

```html

---
title: Sample post
posturl: https://www.example.com/blogs/2024-04-16-sample-post/ <--- creates url in markdown frontmatter
---

```
I don't see any examples in the Decap CMS documentation, so I was wondering if it is possible to do it.
