### DISCUSSION TITLE
Second layout with second URL for same page

### DISCUSSION THREAD

**Discussion by denclade** [11ty/eleventy#3520] [Q&A] [answered]
I've setup some pages like /posts/march/todo.md which renders with a .njk template to bla.com/posts/march/todo. I would like to create an additional link like bla.com/posts/march/todo/iframe which contains the same page, but with another Layout file. Is there an easy way to achive something like that?

An alternative would be to to something like /posts/march/todo?iframe and hide all unwanted content via JavaScript in one layout. But I would prefer a solution without JS.

**Comment by denclade** [comment, marked as answer]
It was simpler as expected, I solved by just adding a new permalink:

```
---
layout: iframe-post.njk
tag: post_iFrame
pagination:
  data: collections.posts
  size: 1
  alias: post
permalink: "/{{post.filePathStem}}/iframe/"
eleventyComputed:
    importantPropertyForIFrame: "{{ post.importantPropertyForIFrame }}"
---
```
