### DISCUSSION TITLE
Pagination collection with tag getting zero results

### DISCUSSION THREAD

**Discussion by stevenvachon** [11ty/eleventy#3690] [Q&A]
```yaml
---
eleventyComputed:
  title: Category Archive for "{{ tag }}"
layout: blog-posts.njk
pagination:
  data: collections."blog-post"
  size: 1
  alias: tag
permalink: /blog/category/{{ tag }}/
---
```
But the results are empty. I have many (markdown) files in the same directory containing the "blog-post" tag.
