### DISCUSSION TITLE
Using filters in front matter

### DISCUSSION THREAD

**Discussion by stevenvachon** [11ty/eleventy#3691] [Q&A] [answered]
Notice the `formatCategoryTag` in the following example:
```yaml
---
eleventyComputed:
  title: Category Archive for "{{ tag | formatCategoryTag }}"
layout: blog-posts.njk
pagination:
  data: collections
  size: 1
  alias: tag
  filter:
    - all
    - blog
    - blog-archives
    - blog-page
    - blog-posts
    - contact-page
    - homepage
permalink: /blog/category/{{ tag | formatCategoryTag }}/
robots: noindex
---
```

Can it not reference such in my _eleventy.config.mjs_?:
```js
export default config => {
  config.addFilter('formatCategoryTag', tag => tag.replace('blog-category-', ''));
  // return { ... };
};
```

If I must use `eleventyComputed`, can the filter be defined in _eleventy.config.mjs_? I unsuccessfully attempted this:
```js
config.addGlobalData('formatCategoryTag', () => {
  return tag => tag.replace('blog-category-', '');
});
```
