### DISCUSSION TITLE
how create correct locale_url for pages that created from data?

### DISCUSSION THREAD

**Discussion by Dexus** [11ty/eleventy#3718] [Q&A] [answered]
I have a file `/de/releases/releases-modules.njk` which contains following:

```
---
pagination:
  data: githubOrgReleases
  size: 1
  alias: ghdata
  addAllPagesToCollections: true
permalink: "/{{lang}}/releases/{{ ghdata.name | slugify }}/index.html"
eleventyComputed:
  title: "Releases of {{ ghdata.name }}"
  eleventyNavigation:
    key: "release-modules-{{ ghdata.name | slugify}}"
    title: "{{ ghdata.name }}"
    parent: "release"
    category: "modules"
    description: "{{ ghdata.description }}"
    order: 100
---

bla blub content
```

How do I now get the the right links for a single page? 

```
{% set pageLinks = page.url | locale_links %}
{% if pageLinks.length >= 1 %}
	<p class="pb-1">Also available translation: {% for link in pageLinks -%}
		{%- if not loop.first %}, {% endif %}
			<a href="{{link.url}}" lang="{{link.lang}}" hreflang="{{link.lang}}">{{link.lang | localeName}}</a>
		{%- endfor %}
	</p>
{% endif %}
```

This is currently gives me the my current language and the other languages, and that also for each page that is created by the template.

I would like to get for `/de/release/app-name` only the result for `/en/releases/app-name-english`

it only works not for sites from data generated... and I don't know how I can fix this.

**Comment by scottsweb** [comment]
This sounds very similar to the issue described here: https://github.com/11ty/eleventy/issues/3555 and there is a potential work around in the comments.

**Reply by Dexus** [reply]
That workaround is crap, because it's more then stupid to disable the pagination or something like that. So no the workaround is not working.

**Reply by Dexus** [reply, marked as answer]
Not the quit best solution but this works, with a computed PageID:

```
  eleventyConfig.addFilter("mapWithLang", function (data) {
    return data.map((x) => {
      return {
        url: x.url,
        lang: x.data.page.lang
      }
    });
  });

  eleventyConfig.addFilter("getByNotPageLang", function (data, lang) {
    if (!lang) return data.filter((x) => x.page.lang != this.page.lang)
    return data.filter((x) => x.data.page.lang != lang)
  });

  eleventyConfig.addFilter("getByPageID", function (data, pageID) {
    return data.filter((x) => {
      //x.page.url.toString().includes('release') && console.log(x.page.url , Object.keys(x.data.eleventyComputed), x.data)
      //console.log({url: x.page.url, xPageID:x.eleventyComputed.pageID, pageID})
      return x.data.pageID == pageID
    });
  });
```

and

```
pagination:
  data: githubOrgReleases
  size: 1
  alias: ghdata
  addAllPagesToCollections: true
permalink: "/{{lang}}/releases/{{ ghdata.name | slugify }}/index.html"
eleventyComputed:
  title: "Releases of {{ ghdata.name }}"
  pageID: "release-modules-{{ ghdata.name | slugify }}"
  eleventyNavigation:
    key: "release-modules-{{ ghdata.name | slugify}}"
    title: "{{ ghdata.name }}"
    parent: "release"
    category: "modules"
    description: "{{ ghdata.description }}"
    order: 100
numberOfLatestPostsToShow: 5
---
```


```
{%- set currentPage = collections.all | getByPageID(pageID) | getByNotPageLang | mapWithLang -%}
{% set pageLinks = page.url | locale_links %}
{%- if currentPage.length > 0 and pageID -%}
  {%- set pageLinks = currentPage -%}
{%- endif -%}
{% if pageLinks.length >= 1 %}
  <p class="pb-1">{{ 'common.alsoavailablein' | t }} {% for link in pageLinks -%}
      {%- if not loop.first %}, {% endif %}
      <a href="{{link.url}}" lang="{{link.lang}}" hreflang="{{link.lang}}">{{link.lang | localeName}}</a>
    {%- endfor %}
  </p>
{% endif %}
```
