### DISCUSSION TITLE
Accessing Global Data File

### DISCUSSION THREAD

**Discussion by gabidombrowski** [11ty/eleventy#3767] [Uncategorized]
I have a yaml data file at `/src/_data/authors.yaml` that includes a list of authors like this:

```yaml
author-name:
  full_name: First Last
  display_name: Display Name
  avatar: avatar.jpg
  bio: "I am an author"
```

I also have a nunjucks template at `/src/author.njk` with the following.

```html
---
layout: base
pagination:
  data: authors
  size: 1
  alias: author
permalink: /blog/authors/{{ author | slug }}/
---

<article>
  {{ authors | log }}
  {{ author | log }}
  {{ content | safe }}
</article>
```

The authors log at author.njk returns an empty object `{}` here and the author log only returns the author slug/key, "author-name" in this case. It looks like `collections.authors` is an empty array.

I need access to the specific authors entry in the yaml data file for this template.

**Comment by bobmonsour** [comment]
Looking at the [11ty docs on Global Data](https://www.11ty.dev/docs/data-global/), it seems that only json files or javascript that returns data can be used this way. I'd suggest adding an authors.js file to your _data directory and add a script that returns the result of converting the YAML to json.

**Reply by gabidombrowski** [reply]
I've configured the custom file format for yaml as per this:

https://www.11ty.dev/docs/data-custom/

There are other places where the authors data is accessible.

**Comment by bobmonsour** [comment]
I wasn't aware of custom data. Thanks for educating me.

**Comment by ironnysh** [comment]
Hi @gabidombrowski, I think [you need to loop over](https://www.11ty.dev/docs/pagination/) the collection with something like:

```njk
<ul>
{%- for author in authors %}
  <li>{{ author }}</li>
{% endfor -%}
</ul>

```

**Comment by bobmonsour** [comment]
I did some digging and testing and came up with the following to make pagination work with the YAML file (though I had to alter the YAML...see below.

First, I changed the YAML file to this:

```YAML
- full_name: Gabi Dombrowski
  display_name: Gabi Dombrowski
  avatar: gabi_avatar.jpg
  bio: "I am one author"
- full_name: Bob Monsour
  display_name: Bob Monsour
  avatar: bob_avatar.jpg
  bio: "I am another author"
```

Then, as you noted, I added the following lines to the eleventy config file to support YAML as a custom data format:

```js
import yaml from "js-yaml";

eleventyConfig.addDataExtension("yml, yaml", (contents) =>
  yaml.load(contents)
);
```

Then, in the authors.njk, I changed it to this:

```yaml
---
layout: base.njk
pagination:
  data: authors
  size: 1
  alias: author
permalink: /blog/authors/{{ author.full_name | slugify }}/
---
```

```html
<article>
  {{ author.full_name }}
  {{ author.bio }}
  {# add more here as needed #}
</article>
```

Hope this helps.
