### ISSUE TITLE
[Pagination] - introduce startPortion parametr or different chunk size for first paginated page

### ISSUE THREAD

**Issue by bodurkalukasz** [11ty/eleventy#1036]
Hi, 
im trying to do a blog main page, where i will have 10 'latest' entries.

What i would like for pagination is to have this 10 entries on main page but then paginate for 24 entries. Is it possible with current setup? 

What comes to my mind at first is to have something like:

```
---
pagination:
  data: collections.posts
  startSize: 10
  size: 24
  alias: posts
---

```

Then, pagination would do that out of the box.
