### ISSUE TITLE
Apply alias variable to global variable returns [Object object]

### ISSUE THREAD

**Issue by code-mattclaffey** [11ty/eleventy#1118]
**Describe the bug**
I am trying to set the global title and description of a dynamic page by doing the following:

```njk
---
pagination:
    data: medium.posts
    size: 1
    alias: post
permalink: "posts-medium/{{ post.title | slug }}/"
title: {{ post.title }}
description: {{ post.shortDescription }}
layout: layouts/home.njk
---
```

The permalink works fine however the title and the description does not work in the same way. 

**To Reproduce**
Example data returning back from my medium post:

data/medium.js
```js
module.exports = {
posts: [
  { 
    title: 'The PWA game',
    shortDescription: '<p class="medium-feed-snippet">Offline is becoming a standard thing to do in web applications because they allow your website to feel like an app. In the modern web most...</p>' 
   }
]
}
```

_includes/header/header.njk

```njk
<header class="o-region c-header">
  <div class="o-region__inner c-header__container">
    <div>
      <h1 class="e-heading e-heading--h2 c-header__heading">
        <span class="c-header__heading-highlight" style="--header-highlight-color: var(--secondary);">{{metadata.title}}</span>
              {% if title %}
                <span class="c-header__heading-highlight c-heading__heading-sub-heading" style="--header-highlight-color: var(--secondary-light)">{{title}}</span> 
              {% endif %}
      </h1>
        {% if description or global.INTRO %} <p class="e-text u-text--short u-text--larger@md">{{description or global.INTRO}}</p> {% endif %}
    </div>
  </div>
</header>
```

/posts/posts.njk
```njk
---
pagination:
    data: medium.posts
    size: 1
    alias: post
permalink: "posts-medium/{{ post.title | slug }}/"
title: {{ post.title }}
description: {{ post.shortDescription }}
layout: layouts/home.njk
---
```

**Expected behavior**
I expected the post.title would show on the page instead of [object Object].

**Screenshots**
![Screenshot 2020-04-25 at 12 44 50](https://user-images.githubusercontent.com/10598938/80278993-94825b00-86f2-11ea-99e1-f586e8ac3906.png)

**Comment by Ryuno-Ki** [comment]
`[object Object]` is `{}.toString()`. That is, you're passing an object instead of a string.
Can you check with [dump](https://mozilla.github.io/nunjucks/templating.html#dump) what's in those objects?

**Comment by code-mattclaffey** [comment]
To fix the issue it was using something in the docs called renderData...

```
---
pagination:
    data: blog.posts
    size: 1
    alias: post
permalink: "blog/{{ post.title | slug }}/"
layout: layouts/post.njk
renderData:
    title: "{{ post.title }}"
    desc: "{{ post.shortDescription }}"
---

```

and then to reference it on the page it was:

```html
<title>{{title or (renderData and renderData.title)}}</title>
<meta name="description" content="{{description or (renderData and renderData.desc)}}" />
```

**Comment by DannyJoris** [comment]
For reference, `renderData` is now deprecated in favour of `eleventyComputed`: https://www.11ty.dev/docs/data-computed/ , so the example would become:

```
---
pagination:
    data: blog.posts
    size: 1
    alias: post
permalink: "blog/{{ post.title | slug }}/"
layout: layouts/post.njk
eleventyComputed:
    title: "{{ post.title }}"
    description: "{{ post.shortDescription }}"
---
```
Which means you can keep the original variables in place.
```
<title>{{ title }}</title>
<meta name="description" content="{{ description }}" />
```
