### ISSUE TITLE
Computed data: can’t access collection data that’s been generated by pagination

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#1138]
**Describe the bug**
I have a global data file, `venues.js`, which I use to create pages from using pagination:

```yaml
---
layout: venue
pagination:
  data: venues
  size: 1
  alias: venue
  addAllPagesToCollections: true
permalink: "venues/{{ venue.id }}/"
tags: venue
eleventyComputed:
  title: "{{ venue.title }}"
---
```

Using `tags`, I add these generated pages to a collection called `venue`.

For my events pages, I want to reference data in `collections.venue`, namely finding the venue which has the same id as the one in an event’s frontmatter. I tried doing this using computed data:

```js
module.exports = {
  layout: 'event',
  permalink: 'events/{{ page.date | date: "%Y/%m" }}/{{ page.fileSlug }}/',
  tags: ['event'],
  eleventyComputed: {
    venue: data => data.collections.venue.find(venue => {
      return venue.id === data.venue_id;
    })
  }
};
```

This generates an error: `Cannot read property 'find' of undefined`. If, however, I query a collection that has not been generated using pagination, then I don’t get this error.

Is this a known limitation of computed data?
