### ISSUE TITLE
Can’t use a collection loop on a paginated page

### ISSUE THREAD

**Issue by paulrobertlloyd** [11ty/eleventy#115]
Given the following document:

```
layout: layouts/index
title: My index page
pagination:
  data: collections.foos
  size: 12
```

and the following layout, `layouts/index.liquid`:

```
{% for foo in pagination.items %}
    {{ foo.data.title }}
{% endfor %}
{% for bar in collections.bars %}
    {{ bar.data.title }}
{% endfor %}
```

(Simplified example)

the `pagination.items` loop is output, but the content within `collections.bars` is not. If I want to include the results of a second collection on the same page, I can’t without deactivating pagination.

Use case: Listing available archives on a blog index page (where archives are in a collection).
