### ISSUE TITLE
Eleventy skips building paginated pages if the collection is empty. How do I build the page anyway?

### ISSUE THREAD

**Issue by MaybeThisIsRu** [11ty/eleventy#1185]
I have a `notes.liquid` page with the following front-matter:

```
---
layout: default
title: Notes
pagination:
    data: collections.notes
    size: 10
permalink: "/notes/{% if pagination.pageNumber > 0 %}{{ pagination.pageNumber + 1 }}/{% endif %}"
---
```

The `notes` collection is empty. In this case, the page does not build. Navigating to `/notes/` returns the following error in a browser:

```
Cannot GET /notes/
```

Removing pagination as follows:

```
---
layout: default
title: Notes
content-description: Paginated page for notes
changeFrequency: daily
permalink: "/notes/"
---
```

...and then visiting the route works.

It seems Eleventy is not building the page is the collection is empty. Is it possible to change this behaviour? I'd like to display a small piece of paragraph instead of a paginated list on such a page, so I'd like for the page to still build.
