### ISSUE TITLE
How to access a data file named 'tags' in pagination?

### ISSUE THREAD

**Issue by winston0410** [11ty/eleventy#1232]
How can I access a global data file named 'tags' in pagination?  This file lives in `_data` and it is json.

When I use the following front matter, it gets the data from the `tags: tag` in front matter.

Code I am using:

```
---
eleventyNavigation:
  key: tag
  parent: tags
pagination:
  data: tags
  size: 1
  alias: tag
permalink: "tags/comic/"
tags: tag
title: {{ tag.name }}
excerpt: Category description
---
```
