### ISSUE TITLE
{{title}} of pages created with data from a data file renders { '[object Object]': null } 

### ISSUE THREAD

**Issue by winston0410** [11ty/eleventy#1239]
**Describe the bug**

{{title}} of pages created with data from a data file renders { '[object Object]': null }, instead of showing the data correctly.

**To Reproduce**

1. Create a json file with the path of `_data/article.json`

```
[
  {
    "id": 1,
    "Title": "This is a test article",
    "created_at": "2020-05-31T05:00:47.109Z",
    "updated_at": "2020-06-02T16:10:40.496Z",
    "Content": "Content of a test article",
    "category": {
      "id": 1,
      "Name": "Test category",
      "created_at": "2020-05-31T05:01:03.125Z",
      "updated_at": "2020-06-02T02:22:28.868Z",
      "categoryName": "Test Category",
      "slug": "test-category",
      "description": null
    },
    "slug": "this-is-a-test-article",
    "user": {
      "id": 1,
      "username": "kghugo",
      "email": "kghugo2000@protonmail.com",
      "provider": "local",
      "confirmed": true,
      "blocked": false,
      "role": 1,
      "created_at": "2020-05-30T14:50:23.243Z",
      "updated_at": "2020-06-02T16:10:40.580Z",
      "Bio": "This is my bio",
      "socialMedia": {
        "id": 1,
        "Facebook": "facebook.com/howto",
        "Twitter": "twitter.com/howto",
        "Website": "survivalisthk.com",
        "Instagram": "instagram.com/howto"
      }
    },
    "featureImage": null,
    "tags": [

    ],
    "comments": [

    ]
  }
]
```

2. Create a template` article.njk `in the path of `articles/article.njk`

3. Set `pagination` to generate that page using `article.njk` as template.  Set `title` in front matter also.

```
---
pagination:
  data: articles
  size: 1
  alias: article
  addAllPagesToCollections: true
permalink: "articles/{{ article.slug }}/"
tags: posts
title: {{ article.Title }}
---
```

4. Do `{{ title | log }}` in article.njk to see the error.

**Expected behavior**

I expect I can get the title with `{{title}}`, even if that page is generated with data

**Screenshots**

**Environment:**

- OS and Version: [e.g. Windows/Mac/Linux]
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`]

**Additional context**

**Comment by winston0410** [comment]
Today I also tried to get `{{permalink}}` in the template file, but it returns as a string instead of variable.  Is there any fix to this?

Front matter:

```
---
pagination:
  data: users
  size: 1
  alias: user
  addAllPagesToCollections: true
permalink: "{% for article in user.articles %}@{{ user.username }}/{{ article.slug }}/{% endfor %}"
---
```

Then I use `{{ permalink | log }}` to get the result, it returns `{% for article in user.articles %}@{{ user.username }}/{{ article.slug }}/{% endfor %}`
