### ISSUE TITLE
Pagination render template from empty array in global data file.

### ISSUE THREAD

**Issue by winston0410** [11ty/eleventy#1257]
**Describe the bug**

Pagination render template from global data file, even the array is empty.  It either resulted in duplicating file with identical path, or `EISDIR: illegal operation on a directory, open 'dist/.'`

**To Reproduce**

1. Create a template file with nested pagination

`**users.njk/article.njk**`

```
---
pagination:
  data: users
  size: 1
  alias: user
  addAllPagesToCollections: true
tags: article
permalink: "{% for article in user.articles %}{{ user.username }}/{{ article.slug }}/{% endfor %}"
---
```

2. Create a global data file, with a ` articles` array being empty
`**users.json**`

```
[
      {
        "username": "example",
        "articles": [
          {
            "title": "This is a test article",
            "slug": "this-is-a-test-article"
          }
        ]
      },
      {
        "username": "zarya",
        "articles": []
      }
    ]
```

3. Run `eleventy`

```
`TemplateWriterWriteError` was thrown

> EISDIR: illegal operation on a directory, open 'dist/.'
```

**Expected behavior**
11ty should ignore ignore empty array and do not write template from it.

**Screenshots**

**Environment:**

- OS and Version: [e.g. Windows/Mac/Linux]
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`]

**Additional context**
