### ISSUE TITLE
Permalink: false not working

### ISSUE THREAD

**Issue by winston0410** [11ty/eleventy#1258]
**Describe the bug**

`Permalink: false `does not work as described in documentation.

**To Reproduce**

1. Create a new file with the following front matter:

```
---
eleventyNavigation:
  key: logout
  order: 4
  parent: home
  url: "#"
tags: menu
 permalink: false
---
```

2. Run `eleventy`

3. Get error

```
`TemplateWriterWriteError` was thrown
> The "path" argument must be of type string. Received type boolean (false)

`TypeError` was thrown:
    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (false)
        at validateString (internal/validators.js:121:11)
        at Object.extname (path.js:1229:5)
```

**Expected behavior**

I expect I can pass boolean in permalink.

**Screenshots**

**Environment:**

- OS and Version: [e.g. Windows/Mac/Linux]
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`]

**Additional context**
