### ISSUE TITLE
pathPrefix and url filter not working on paginated pages

### ISSUE THREAD

**Issue by nickdunn** [11ty/eleventy#1304]
I am using pagination to generate a list of jobs:

```
---
title: Job
layout: default
pagination:
    data: jobs
    size: 1
    alias: job
permalink: ("/jobs/{{ job.title | slug }}-{{ job.id }}/" | url)
---
```
and I have just started using the `pathPrefix` config as my site will live in a sub-folder of a domain:

```
pathPrefix: "/careers/digital/"
```

I have a primary nav in my base layout with a link such as:

    <li><a href="{{ "/jobs" | url }}">Find roles</a></li>

Which on most pages correctly outputs as:

    <li><a href="/careers/digital/jobs">Find roles</a></li>

However on the pages generated from pagination, the pathPrefix is not appended: 

    <li><a href="/jobs">Find roles</a></li>

The paginated pages themselves are correctly generated though, at:

    /careers/digital/jobs/{title}-{id}/

**Environment:**

- macOS 10.14.6
- Eleventy Version 0.11.0
- Node v12.14.1
