### ISSUE TITLE
Is it possible to put an `index.md` file containing a list of articles (paginated) inside the `articles` folder?

### ISSUE THREAD

**Issue by adamsilver** [11ty/eleventy#1319]
I want this:

```
/articles
  articles.json
  index.md
  2020-06-01-article-title-1.md
  2020-07-02-another-article-title-1.md
```

`articles.json` contains:

```
{
  "layout": "article.njk",
  "permalink": "/articles/{{page.fileSlug}}/index.html",
  "tags": ["article"]
}
```

`index.md` contains the following frontmatter:

```
---
eleventyExcludeFromCollections: true
layout: page
title: Articles
navId: articles
heading: Articles
permalink: /articles/
sub: I write regularly about my work as a designer, focusing on simplicity and accessiblity.  Here's my [RSS feed](/atom.xml).
pagination:
  data: collections.article
  size: 15
  alias: article
  reverse: true
---
```

When I do this console output:

```
> Output conflict: multiple input files are writing to `dist/articles/articles/index.html`. Use distinct `permalink` values to resolve this conflict.
  1. ./src/articles/index.md
  2. ./src/articles/index.md
  3. ./src/articles/index.md
  4. ./src/articles/index.md
```

Any ideas please?
