### ISSUE TITLE
eleventyComputed in YAML front matter ignoring some variables

### ISSUE THREAD

**Issue by WebShapedBiz** [11ty/eleventy#1328]
Hi.

I'm using eleventyComputed in YAML front matter on my blog post `njk` template like this:
```
---
layout: layouts/default.njk
eleventyComputed:
    title: "{{ post.title }}"
    description: "{{ post.excerpt }}"
    url: "{{ post.url }}"
    published: "{{ post.published_at }}"
    updated: "{{ post.updated_at }}"
    author: "{{ post.primary_author.url }}"
---
```
Template strings for both `title` and `description` variables are correctly rendered in `default.njk` layout, but the rest of them are just passed and rendered like strings, i.e. `{{ post.url }}`.

What am I not getting here?

- OS and Version: elementaryOS 5.1.6 Linux
- Eleventy Version: 0.11.0

Thanx for the help.
