### ISSUE TITLE
Issue with pagination using data files and permalinks

### ISSUE THREAD

**Issue by Vassi** [11ty/eleventy#135]
One thing I'm struggling with is whether I can use the alias data in other frontmatter for the page. The permalink example seems to imply I can do this:

given: posts.json
```
{
  "articles":
  [
    {
      "title": "Do you even paginate bro?",
      "author": "Bill Ted",
      "publish_date": "2018-06-22",
      "tags": [
        "post"
      ],
      "image": "/url/thing",
      "teaser": "Teaser copy",
      "body": "<p>Raw HTML</p>"
    }
  ]
}
```

then this template:
```
---
pagination:
  data: posts.articles
  size: 1
  alias: article
permalink: blog/{{article.title | slug}}/index.html
layout: layouts/base
navtitle: {{article.title}}
author: {{article.author}}
tags: {{article.tags}}
date: {{article.publish_date}}
teaser: {{article.teaser}}
---
{{article.body | safe}}
```

all I get is a progression of errors:
Problem writing eleventy templates: 
TypeError: data.date.toLowerCase is not a function
    at Template.getMappedDate (/Users/CAR0051/Source/nm-innovation-hub-gen/node_modules/@11ty/eleventy/src/Template.js:598:23)
    at <anonymous>

if I remove the date from frontmatter:
Problem writing eleventy templates: 
{ Template render error: (unknown path)
  Error: slugify: string argument expected

if i remove the permalink I get my output, but my title, for instance, shows up like this: 
```
<title>[object Object]</title>
```

Am I doing something eleventy doesn't want me to do? Is pagination only good to iterate over collections? I have a data file of posts that I was hoping to use, but I suppose I can use custom code to create the njk files out of my JSON and then let eleventy build the paginated list pages.

**Comment by Vassi** [comment]
Sorry if my original message sounds kinda jerk-ish, I was kind of frustrated when I wrote it.

So I worked around this by pre-generating njk templates into my site before running eleventy, which allows me to have my posts and then use the collection for the listing pages. This is fine, I guess I just really wanted to use paginate as it seemed like it could do the job. If I was doing something wrong I would still prefer to use pagination.

**Comment by zachleat** [comment]
Tests added around this and it’ll be included with the next minor version. Thanks!

**Comment by zachleat** [comment]
Lotta clean up in that commit but the test case is at https://github.com/11ty/eleventy/commit/d4380760a4442bb234cb26f464cf60cb7266f43d#diff-9b8aacd59d9561a176ffd95154d5eaf2

**Comment by asherweintraub** [comment]
I know this is super old, but I'm having this exact issue.

Here's my front matter:

```yaml
---
layout: noblock
tags: products
pagination:
  data: shopify.products
  size: 1
  alias: product
  addAllPagesToCollections: true
title: {{ product.title }}
permalink: /shop/products/{{ product.handle }}/
---
```
I've tried with/without the trailing slash, `index.html` and the `slug` filter. No luck- I always get
```
Problem writing Eleventy templates: (more in DEBUG output)
    Error: slugify: string argument expected
```

I've gotten around this until now by using an eleventy data file instead:

_shop.11tydata.js_
```js
const slugify = require('slugify');

module.exports = {
  eleventyComputed: {
    permalink: data => {
      return `/shop/products/${slugify(data.product.handle)}/`
    }
  }
};
```
but naturally I'd rather just throw it in the front matter and be done with it.
