### ISSUE TITLE
Output subset of data in collection

### ISSUE THREAD

**Issue by Grant-Smith-74** [11ty/eleventy#1371]
I have a featuredProducts collection, from which I wish to output a carousel of images. My front matter includes the following…
```
---
carousel:
  - image: '/assets/img/img.jpg'
    imageAlt: 'text'
  - image: '/assets/img/img-02.jpg'
    imageAlt: 'text'
  - image: '/assets/img/img-03.jpg'
    imageAlt: 'text'
  - image: '/assets/img/img-04.jpg'
    imageAlt: 'text'
  - image: '/assets/img/img-05.jpg'
    imageAlt: 'text'
---
```
And then my partial calls the carousel.
```
{% set allProductPosts = collections.featuredProduct -%}
{% for item in allProductPosts -%}
  <figure class="outer-5by3">
    <img loading="lazy" class="inner-5by3" src="{{ item.data.carousel.image }}" alt="{{ item.data.carousel.imageAlt }}">
  </figure>
{% endfor -%}
```
However, the resulting output has empty src and alt attributes? And I do not understand why? My only guess is that it has something to do with how I am trying to loop through the subset of front matter?

Within the same featuredProducts collection, I have a main image defined in the front matter as…
```
---
img_main:
  image: '/assets/img/img.jpg'
  imageAlt: 'text'
---
```
With the following template…
```
{% for item in collections.featuredProduct -%}
  <div class="product_carousel_cell">
    <figure class="outer-5by3">
      <img class="inner-5by3" src="{{ item.data.img_main.image }}" alt="{{ item.data.img_main.imageAlt }}" loading="lazy" />
    </figure>
  </div>
{% endfor -%}
```
And this results in the desired output.
```
<div class="product_carousel_cell">
  <figure class="outer-5by3">
    <img class="inner-5by3" src="/assets/img/img.jpg" alt="text" loading="lazy" />
  </figure>
</div>
```
Hence why I assumed `item.data.carousel.image` would work?
