### ISSUE TITLE
Option to paginate over objects (instead of just arrays)

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#139]
Right now Pagination only works with arrays and not objects.

Related:
```
---
pagination:
  data: collections
  size: 1
  alias: tag
permalink: /tags/{{ tag }}/
---
```

from https://github.com/11ty/eleventy/issues/134#issuecomment-393896921
