### ISSUE TITLE
Trouble with permalinks in pagination

### ISSUE THREAD

**Issue by WebShapedBiz** [11ty/eleventy#1415]
Hi.

I'm pulling the data from an LMS system with `_data/activecourses.js`, and when I want to list them on a page this works perfectly.
```
{% for course in activecourses %}
{{ course.name }}
{% endfor %}
```

However, when I try to create a single course page the pagination is giving me so much grieve.
This:
```
---
pagination:
    data: activecourses
    size: 1
    alias: activecourse
permalink: "/some-path/{{ activecourse.name | slug }}/index.html"
layout: layouts/layout-page.njk
---
```
is giving me this error: `Error: slugify: string argument expected` which tells me that my course was not picked from the collection and `slugify` has no string to work with.

Funny thing happens when I try with this:

```
---
pagination:
    data: activecourses
    size: 1
permalink: "/some-path/{{ activecourses[0].name | slug }}/index.html"
layout: layouts/layout-page.njk
---
```
is throwing me an error: `Error: Output conflict: multiple input files are writing to ... Use distinct `permalink` values to resolve this conflict.`, which tells me that I'm able to pick a single course out of the collection and it's always the same, [0], so the path for that iteration is the same, hence the error. If I change `activecourses[0]` to `activecourses[1]` I correctly get the next course in my collection with, of course, the same error.

Question: how can I iterate through `activecourses` Array within my pagination? I'm using the same technique on the other project to pull the data from Ghost API and everything works fine since the Ghost's payload is giving me an Object and not an Array.

My setup:
OS: eleventyOS Linux 5.1.7. (Ubuntu 18.04 based)
Nodejs: v12.16.1
npm: v6.14.2
Eleventy: 0.11.0

Cheers.
