### ISSUE TITLE
Plugin gets called twice if first property passed to it is a single quoted string. 

### ISSUE THREAD

**Issue by dwkns** [11ty/eleventy#1729]
**Describe the bug**
I'm calling my `addShortcode` plugin from with `eleventyComputed` in my Front Matter. The ultimate goal is to dynamically generate OpenGraph images from page data. 

If the first value passed in is not a "real" string the plugin it gets called twice.

**To Reproduce**

The plugin:

```js
// .eleventy.js
const generateOGImage =  {
  initArguments: {},
  configFunction: function(eleventyConfig, options = {}) {

      eleventyConfig.addShortcode("ogCreateImage", function(props) {
        const imageName = props.ogImageName || options.ogImageName || 'defaultImageName'
        const imageTemplate = props.ogImageTemplate || options.ogImageTemplate ||  'defaultImageTemplate'
        const imageText = props.ogImageText ||  'This should not be called'

      console.log('-----------------ogCreateImage-----------------');
      console.log(`filename: ${imageName}`);
      console.log(`using template: ${imageTemplate}`);
      console.log(`with the text : ${imageText}`);
      console.log('-----------------------------------------------');

      // call  the image creation code — return filename with extension
      // const imageNameWithExtension = createOGImage(imageName, imageTemplate, imageText) 

      const imageNameWithExtension = `${imageName}.png` //mock it for now
      return imageNameWithExtension
     });

  }
};

module.exports = function (eleventyConfig) {

  eleventyConfig.addPlugin(generateOGImage, {
  });

 eleventyConfig.addFilter("realString", function(value) {
    return value.toString();
  });

  return {};
};
```

Then in your template `index.njk`

```yaml
---
title: "Some title here"
eleventyComputed:
    ogImageURL: "{% ogCreateImage {  ogImageName: 'some-string', ogImageTemplate: 'page-blank.png', ogImageText: title } %}"
---
Template Content
```
Produces:
```bash
$ npx @11ty/eleventy
-----------------ogCreateImage-----------------
filename: some-string
using template: page-blank.png
with the text : This should not be called
-----------------------------------------------
-----------------ogCreateImage-----------------
filename: some-string
using template: page-blank.png
with the text : Some title here
-----------------------------------------------
Writing _site/index.html from ./index.njk.
Wrote 1 file in 0.03 seconds (v0.12.1)
```
The plugin is called twice. First time `eleventyComputed` data is `undefined`

However when you pass `title | realString` as the first argument; or as below convert it to a `slug` — It works as expected.

```yaml
---
title: "Some title here"
eleventyComputed:
    ogImageURL: "{% ogCreateImage  {  ogImageName: title | slug, ogImageTemplate: 'page-blank.png', ogImageText: title } %}"
---
Template Content
```
Produces:

```bash
$ npx @11ty/eleventy
-----------------ogCreateImage-----------------
filename: some-title-here
using template: page-blank.png
with the text : Some title here
-----------------------------------------------
Writing _site/index.html from ./index.njk.
Wrote 1 file in 0.03 seconds (v0.12.1)
```
**Why is this important?**
It means that within the plugin I can't reliably detect if values have been passed in. And that means the image generation code will be run twice.

**Expected behavior**
I should be able to pass a single quoted string as the first argument and the plugin only be called once. 

**Environment**
- macOS Big Sur 11.2.3. Mac Mini M1
```bash
$ npx @11ty/eleventy --version 
0.12.1
```
