### ISSUE TITLE
Pagination breaks when using global data files instead of .11tydata.js

### ISSUE THREAD

**Issue by patrikalienus** [11ty/eleventy#1740]
**Describe the bug**
I'm consuming content from GraphCMS. It works fine when the API is called and data is generated from /r_pages.11tydata.js, but not when it's located in /_data/r_pages.js

**To Reproduce**
I'm gonna include the relevant parts of the code here.

**/_data/r_pages.js:**
```
module.exports = async () => {
	const r_pages_raw = await getPages();

	let localizations;
	let r_pages_full = new Array();

	r_pages_raw.forEach((item, index) => {
		localizations = item.localizations;
		r_pages_full.push(localizations);
	});

	const r_pages = r_pages_full.reduce((acc, items) => [...acc, ...items], []);
	console.log(r_pages);
	return { r_pages };
};
```
**Truncated console.log output:**
```
[
  {
    locale: 'sv',
    id: 'cknp2do2g6zkr0954nky6q2ct',
    pageTitle: 'Case',
    slug: 'case',
    updatedAt: '2021-04-19T20:46:01.584668+00:00',
    createdAt: '2021-04-19T20:42:07.225876+00:00',
    pageContent: { html: '<p></p>' },
    parentPage: [],
    final_slug: 'case',
    pre_slug: ''
  },
  {
    locale: 'en',
    id: 'cknp2do2g6zkr0954nky6q2ct',
    pageTitle: 'Case',
    slug: 'case',
    updatedAt: '2021-04-19T20:46:01.584668+00:00',
    createdAt: '2021-04-19T20:42:07.225876+00:00',
    pageContent: { html: '<p></p>' },
    parentPage: [],
    final_slug: 'case',
    pre_slug: ''
  }
]
```

**/r_pages.njk:**
```
---
tags: "r_pages"
pagination:
  data: r_pages
  size: 1
  alias: r_page
  addAllPagesToCollections: true
permalink: "/{{ r_page.locale }}/{{ r_page.final_slug }}/"
layout: ./layouts/r_pages.njk

eleventyComputed:
  title: "{{ r_page.pageTitle | safe }}"
  slug: "{{ r_page.slug }}"
  lang: "{{ r_page.locale }}"
---
```

**When building, I get this error message:**
```
Problem writing Eleventy templates: (more in DEBUG output)
> Output conflict: multiple input files are writing to `_site/index.html`. Use distinct `permalink` values to resolve this conflict.
  1. ./index.njk
  2. ./r_pages.njk
```

I.e. the slug and locale keys didn't reach the r_pages.njk upon build, but it's clearly available in the console.log output. The console.log output is exactly the same if the file is in the root and named using `.11tydata.js`, btw.

**Expected behavior**
I expect the `r_pages` data to be available for pagination just like it is when using the `.11tydata.js` file format in the root.

**Environment:**
- OS and Version: Mac
- Eleventy Version: 0.12.1

**Additional context**
Perhaps I have screwed something up or neglected looking into something, but per the documentation, as long as a .js file contains a `module.exports` statement, it can live in /_data/ and should then have the .js file extension. So that's why I'm finally posting here - I've exhausted everything.

I think. :)
