### ISSUE TITLE
Allow "title" frontmatter tag to take a template value during pagination

### ISSUE THREAD

**Issue by rockorager** [11ty/eleventy#1758]
## Request

Make the `title` tag in frontmatter work the same way as `permalink` when using pagination

## Example
```
---
pagination:
    data: myData
    size: 1
    alias: myDataItem
permalink: "/path/name/{{ myDataItem.value1 }}"
title: {{ myDataItem.title }}
---
```

This allows pages generated from pagination to have different titles
