### ISSUE TITLE
using `alias: page` in pagination throws error

### ISSUE THREAD

**Issue by andyford** [11ty/eleventy#1794]
given this frontmatter pagination setup:

```
---
pagination:
    data: pages
    size: 1
    alias: page
permalink: "{{ page.slug | slug }}/"
layout: layouts/base.njk
---
```

Eleventy will throw the following error:
```
> mapB.date.getTime is not a function

`TypeError` was thrown:
    TypeError: mapB.date.getTime is not a function
```

This appears to be because of using the name `page` in `alias: page`.

It would be great to support `alias: page` without issue, but it that's not feasible, it would be nice to add this caveat to the documentation.
