### ISSUE TITLE
No maintenance tag pages limited by collection

### ISSUE THREAD

**Issue by tusamni** [11ty/eleventy#1834]
I'm trying to use no maintenance tag pages feature here: https://www.11ty.dev/docs/quicktips/tag-pages/

However, I want to limit it specifically to pull only tags from say a "posts" collection, versus a "shoots" collection. As it is, it pulls all tags in no matter what. I could simply filter out the tags, but then it's not really "no maintenance" as I'd have to keep updating the filter.

So currently it's:
```
pagination:
    data: collections
    size: 1
    alias: tag
permalink: /blog/tags/{{ tag | slug }}/index.html
```

and I'd like to do something like:
```
pagination:
    data: collections.posts
    size: 1
    alias: tag
permalink: /blog/tags/{{ tag | slug }}/index.html
```

However, that is giving me:
`Output conflict: multiple input files are writing to _site/blog/tags/[object Object]/index.html`

**Comment by pdehaan** [comment]
```yaml
pagination:
    data: collections.posts
    size: 1
    alias: tag
permalink: /blog/tags/{{ tag | slug }}/index.html
```

I think the problem is that `tag` here is an object (a post), so it is getting stringified to `[object Object]`, for each item in the collection, which causes an output file naming conflict.

So you might want something unique like `{{ tag.filePathStem | slug }}`. But maybe I'm misunderstanding what you're trying to do and you're trying to loop over all the tags for each post in a collection (which might not be possible using pagination this way and you'll need a custom collection or something since it involves a bit more looping and deduping).
