### ISSUE TITLE
Two tags that differ only in case cause a crash during build

### ISSUE THREAD

**Issue by ijager** [11ty/eleventy#1942]
Two tags that differ only in case cause a crash during build. 11ty will make the tags lower case and try to make the same tag page twice, which causes an error.

For example tags: 
`adc` and `ADC` 
or `Example` and `example`

**To Reproduce**

1. Start with the eleventy base blog: `git clone git@github.com:11ty/eleventy-base-blog.git`

2. In first post add tag `adc`:

```yaml
---
title: This is my first post.
description: This is a post on My Blog about agile frameworks.
date: 2018-05-01
tags:
  - adc
layout: layouts/post.njk
---
```

3. In the second post add tag `ADC`

```yaml
---
title: This is my second post.
description: This is a post on My Blog about leveraging agile frameworks.
date: 2018-07-04
tags:
  - ADC
layout: layouts/post.njk
---
```

4. build the project:

```bash
npm install
npm run build
```

The output is:

```console
$ npm run build

> eleventy-base-blog@5.0.2 build ~/eleventy-tag-bug
> eleventy

Problem writing Eleventy templates: (more in DEBUG output)
> Output conflict: multiple input files are writing to `_site/tags/adc/index.html`. Use distinct `permalink` values to resolve this conflict.
  1. ./tags.njk
  2. ./tags.njk

`DuplicatePermalinkOutputError` was thrown:
    (Repeated output has been truncated…)
        at TemplateMap.checkForDuplicatePermalinks (~/eleventy-tag-bug/node_modules/@11ty/eleventy/src/TemplateMap.js:547:13)
        at TemplateMap.cache (~/eleventy-tag-bug/node_modules/@11ty/eleventy/src/TemplateMap.js:308:10)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async TemplateWriter._createTemplateMap (~/eleventy-tag-bug/node_modules/@11ty/eleventy/src/TemplateWriter.js:170:5)
        at async TemplateWriter.writeTemplates (~/eleventy-tag-bug/node_modules/@11ty/eleventy/src/TemplateWriter.js:203:5)
        at async TemplateWriter.write (~/eleventy-tag-bug/node_modules/@11ty/eleventy/src/TemplateWriter.js:254:25)
        at async Eleventy.write (~/eleventy-tag-bug/node_modules/@11ty/eleventy/src/Eleventy.js:743:13)
Copied 3 files / Wrote 0 files in 0.23 seconds (v0.12.1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eleventy-base-blog@5.0.2 build: `eleventy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the eleventy-base-blog@5.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

It is trying to create this tag page *twice*: `_site/tags/adc/index.html`.  And then errors.

**Expected behavior**

I would expect it to 
1. First convert tags to lower case, 
2. then merge/deduplicate, 
3. then generate tag pages

**Environment:**

- OS and Version: MacOS 10.15.7
- Eleventy Version 0.12.1
- NodeJS v12.16.1
