### ISSUE TITLE
Create a collection from pagniation

### ISSUE THREAD

**Issue by nicolas-b12** [11ty/eleventy#1952]
**Describe the bug**
I'm trying to generate a collection by paginating a directory of JSON files but it seems that the tags in the JSON files are ignored.

**To Reproduce**

1. Create a `works` directory in `_data`
2. Fill it with JSON files containing at least a `tags` property.
3. Create a pagination template like this : 
```
---
pagination:
    data: works
    size: 1
    alias: work
    resolve: values
permalink: "{{locale}}/project/{{ work.pageName }}/"
layout: layouts/pages/project.njk
eleventyComputed:
    title: "{{work.title}}"
---
```
4. Pages are generated correctly.
5. In an other page, try to access the collection indicated in the tags in the JSON files.
6. Collection are not created.

**Expected behavior**
We should get access to the collections based on the tags in the JSON files

**Environment:**

- OS and Version: Mac 11.4
- Eleventy Version [via `eleventy --version` or `npx @11ty/eleventy --version`] : 0.12.1
