### ISSUE TITLE
`page.url` should replace path variables in serverless mode.

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#1977]
A serverless path like `/test/:slug/` is currently `/test/:slug/` in serverless rendering. You can use the `serverlessUrl` filter to “render” this image but really `page.url` should be the correct value (normalized using `eleventy.serverless.path`) when in serverless rendering mode.

Not related to https://github.com/11ty/eleventy/issues/1832

Driven from a bug with the Eleventy Screenshot service on https://twitter.com/DavidDarnes/status/1440000831571509250

**Comment by zachleat** [comment]
For future me:

```
---
social:
  imgsrc: https://www.11ty.dev/img/open-graph.jpg
  imgalt: The 11ty logo text with a small floating possum on a balloon
eleventyComputed:
  domain: "{{ process.env.DEPLOY_PRIME_URL or 'https://www.11ty.dev'}}"
  social:
    imgsrc: "https://v1.screenshot.11ty.dev/{{ (domain + page.url) | urlencode }}/opengraph/"
    description: "A docs page for Eleventy {% latestVersion versions, config %}, a simpler static site generator."
---
```

`social.imgsrc` was resolving with `page.url` as `/authors/:name/` and we wanted the serverless data injected there.
