### ISSUE TITLE
Serverless Redirects overwriting redirect conditions

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2392]
The serverless plugin writes redirects for the serverless paths to the `netlify.toml` file. When using `redirect.conditions` as in the following example, those get wiped out!

```
[[redirects]]
from = "/admin/*"
force = true
status = 200

  [redirects.conditions]
  Role = [ "admin" ]

[[redirects]]
from = "/admin/*"
to = "/login/"
force = true
status = 401
```

Reported by @mirisuzanne via https://twitter.com/TerribleMia/status/1526340325358284800

**Comment by zachleat** [comment]
A ha, I see!

### Before

```toml
[[redirects]]
from = "/admin/*"
force = true
status = 200

  [redirects.conditions]
  Role = [ "admin" ]

[[redirects]]
from = "/admin/*"
to = "/login/"
force = true
status = 401

[[redirects]]
from = "/dynamic-path/"
to = "/.netlify/functions/possum"
status = 200
force = true
_generated_by_eleventy_serverless = "possum"
```

### After

```toml
[[redirects]]
from = "/dynamic-path/"
to = "/.netlify/functions/possum"
status = 200
force = true
_generated_by_eleventy_serverless = "possum"

[[redirects]]
from = "/admin/*"
force = true
status = 200

  [redirects.conditions]
  Role = [ "admin" ]

[[redirects]]
from = "/admin/*"
to = "/login/"
force = true
status = 401
```

**Comment by zachleat** [comment]
In 2.0.0-canary.12, these `netlify.toml` additions for serverless will maintain order. Importantly, we can’t know whether or not the entry should be prepended or appended when the entry is first created, but any changes you make to the order will be preserved!

**Comment by mirisuzanne** [comment]
Will changing the order here actually achieve what I need? I'm not sure which order is the proper one. I need the glob to set a role condition first, and then the dynamic path will still apply if set later in the TOML?

**Comment by zachleat** [comment]
You want something like this output right?

```toml

[[redirects]]
from = "/admin/*"
to = "/.netlify/functions/possum"
force = true
status = 200
_generated_by_eleventy_serverless = "possum"

  [redirects.conditions]
  Role = [ "admin" ]

[[redirects]]
from = "/admin/*"
to = "/login/"
force = true
status = 401
```

The above will work fine in the new canary and will maintain the additional `redirects.conditions` there in the toml.

Have I misunderstood?
