### ISSUE TITLE
Pagination and permalink error

### ISSUE THREAD

**Issue by mwinterheller** [11ty/eleventy#2495]
**Describe the bug**
I am following the provided instructions in https://github.com/11ty/eleventy/issues/326#issuecomment-444127344 by using pagination to create two files from one original source.

When the permalink would also incorporate additional variables from a data file, this approach is no longer working and 11ty throws an error on build:

_can not read a block mapping entry; a multiline key may not be an implicit key at line 10, column 1:_

I am not sure if I am just doing it wrong or if this is not supported by 11ty. Either way: Thank you for creating such an amazing product.

### Step by step explanation of error

This is the used YAML where it works - notice no additional variable is used in the `permalink`:
```
pagination:
  data: resultingPages
  alias: resultingPage
  size: 1
resultingPages:
  - a47074c6-e151-441a-942b-0aaa8629915a
  - db6494f3-f8b6-4f76-b209-09df87817e64
permalink: test/projects/{{ resultingPage }}/templates.html
```
**This works fine.**

However, as soon as I would like to incorporate additional dynamic data from a data json (variable: rootfolder) file in the `permalink` like this:

```
pagination:
  data: resultingPages
  alias: resultingPage
  size: 1
resultingPages:
  - a47074c6-e151-441a-942b-0aaa8629915a
  - db6494f3-f8b6-4f76-b209-09df87817e64
permalink: {{ rootfolder }}/projects/{{ resultingPage }}/templates.html
```
I receive the following error:

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble reading front matter from template ./test/projects/available-templates.html (via TemplateContentFrontMatterError)
[11ty] 2. can not read a block mapping entry; a multiline key may not be an implicit key at line 10, column 1:
[11ty]     
[11ty]     ^ (via YAMLException)
[11ty] 
[11ty] Original error stack trace: YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 10, column 1:
```

**To Reproduce**

1. Set up YAML like above with pagination and variable from data file
2. create data json file in file structure above
3. reference variable from data file in permalink

**Expected behavior**
I was expecting the data variable to be available in the YAML just like in the page itself or when not using pagination.

**Screenshots**
not applicable

**Environment:**

- OS and Version: Mac/M1
- Eleventy Version: 1.0.1

**Additional context**
