### ISSUE TITLE
eleventyComputed not working after 2.0.0-canary.8 

### ISSUE THREAD

**Issue by oliwarner** [11ty/eleventy#2512]
I've just upgraded to 2.0.0-canary.14 from 1.0.1. Almost everything worked great except my tag page.

```
---
pagination:
  data: collections
  size: 1
  alias: tag
permalink: /tag/{{ tag | slug }}/index.html
eleventyComputed:
  title: "{{ tag | title }}"
---
<header class="tag">
  <h1>{{ title }}</h1>
</header>
```
I use `eleventyComputed` and a filter to recondition the lowercase tags into something more readable. I do it here so I can use it in the `<title>` tag and OG metadata, as well as on the page.

After upgrading, this doesn't work. `title` is just empty. I've seen [a post on another bug](https://github.com/11ty/eleventy/issues/2365#issuecomment-1127682094) suggesting this crept in 2.0.0-canary.9 but I can't see anybody else having this problem.

**Comment by NotIntelli** [comment]
I'm having the same problem with `eleventyComputed` returning an empty string while paginating
```yaml
title: GenericTitle
pagination:
    data: collections
    size: 1
    alias: tag
permalink: /tags/{{ tag }}/
eleventyComputed:
    code: "_tag{{ tag }}" #Becomes ""
layout: index
eleventyExcludeFromCollections: true
```
`code` just becomes empty. Removing `{{ tag }}` from the computed value still causes `code` to be empty.
```yaml
---
title: GenericTitle
pagination:
    data: collections
    size: 1
    alias: tag
eleventyComputed:
    code: "foo" #Becomes "" when it should be "foo"
permalink: /tags/{{ tag }}/
collection: tag
layout: index
eleventyExcludeFromCollections: true
```
Seems as if `eleventyComputed` doesn't work with pagination at all
