### ISSUE TITLE
Pagination unexpectedly creates pages for custom collections

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#255]
I suspect this may be expected behaviour, but it caught me out - and I wonder if the pagination guidance could be clearer / have some kind of feature flag.

I've set up pagination following [this guide](https://www.11ty.io/docs/quicktips/tag-pages/) so I get a tag page for each tag used on my site. My two tags are currently `design` and `photography`.

I've also got a custom collection (`getTagList`) that returns a list of all tags - [copied from the eleventy-base-blog](https://github.com/11ty/eleventy-base-blog/blob/master/_11ty/getTagList.js).

Following the `getTagList` example, I added a collection for `publicTags` and `privateTags` (my private tags all begin with "_").

Tag pages are generated with:
```
---
pagination:
  data: collections
  size: 1
  alias: tag
  filter:
layout: content-page.njk
renderData:
  title: Tagged “{{ tag }}”
permalink: /tags/{{ tag }}/
---
```

Combined, eleventy outputs
```
/tags/design/index.html
/tags/photography/index.html
/tags/getTagList/index.html
/tags/publicTags/index.html
/tags/privateTags/index.html
```

The last three were very unexpected. I was expecting a page for each tag, and as they're not tags, I didn't expect to see them. I now sort of get that we're paginating on collections itself as a proxy for tags. Maybe this is useful?

I now get why example-blog had 'all' in the pagination filter - this wasn't at all obvious at first.

---

Some thoughts: 
* The tutorial doesn't currently include a filter for `all` - I think this means anyone following it will get a tag page for `all` - which they probably don't want. Can it be added to the tutorial?
* Could there be a `collections.allTags` that's built in, and lists all tags? (rather than users having to provide a custom collection?
* Suggest updating the tutorial to page to use `collections.allTags` rather than page on `collections` directly and risk creating unnecessary pages. Else is there another way of paginating on tags only?

**Comment by edwardhorsford** [comment]
I should add that I worked around the issue by paging on `collections.publicTags` instead:
```
---
pagination:
  data: collections.publicTags
  size: 1
  alias: tag
  filter:
layout: content-page.njk
renderData:
  title: Tagged “{{ tag }}”
permalink: /tags/{{ tag }}/
---
```

And it all worked perfectly. Which quite frankly is magic 🎉 . 

So yay Eleventy. So flexible.
