### ISSUE TITLE
Support a Comma separated list (single string) for `tags`

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#2820]
> One issue with the conversion from Ghost to Markdown is how tags are handled. In the export, multiple tags on a post are comma-separated, like this -

```yaml
---
title: Example Article
slug: example-article
tags: one, two
---
```

via https://bitsofco.de/from-ghost-to-11ty/#tags
