### ISSUE TITLE
Expose page's frontmatter data to transformers

### ISSUE THREAD

**Issue by elmuerte** [11ty/eleventy#2965]
### Is your feature request related to a problem? Please describe.

With #1522 `this.page` was added for transformers. However this page data does not contain any of the front matter data.

```
{
  date: 2023-06-12T17:44:18.978Z,
  inputPath: './src/content/404.html',
  fileSlug: '404',
  filePathStem: '/404',
  outputFileExtension: 'html',
  templateSyntax: 'liquid',
  url: '/404.html',
  outputPath: 'dist/404.html'
}
```

If the frontmatter data was included it would allow pages to inform transformers to take certain actions.

### Describe the solution you'd like

I would like to see the page object to also contain the front matter data

```
{
  date: 2023-06-12T17:44:18.978Z,
  inputPath: './src/content/404.html',
  fileSlug: '404',
  filePathStem: '/404',
  outputFileExtension: 'html',
  templateSyntax: 'liquid',
  url: '/404.html',
  outputPath: 'dist/404.html',
  data {
    title: '404 page',
    myCustomerFrontMatterElement: ['foo', 'bar']
  }
}
```

In case the frontmatter was:

```
---
title: 404 page
myCustomerFrontMatterElement:
  - foo
  - bar
---

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

**Comment by mofosyne** [comment]
Adding my voice here. I was adding a custom location

```
location:
  address: 1 barrack st, masslen, IL USA
  latitude: -45.862
  longitude: 24.7844
  name: 'Top NEP Engineering Products'
  description: 'Venue for neptunia fans gathering'
```

and while it works when doing pagenation, I was unable to directly access it via what I was expecting to be `{{page.data.location | json}}`
