### ISSUE TITLE
EleventyHtmlBasePlugin not updating URLs in CSS files

### ISSUE THREAD

**Issue by tedw** [11ty/eleventy#3004]
### Operating system

macOS 13.3.1

### Eleventy

2.0.1

### Describe the bug

I just tried using the [HTML <base> plugin](https://www.11ty.dev/docs/plugins/html-base/) for the first time and it worked great—except it didn’t update any URLs in my CSS file.

I’m loading various web fonts like this locally:

```css
@font-face {
  font-display: fallback;
  font-family: "Manrope";
  font-style: normal;
  font-weight: 400;
  src: url("../fonts/manrope/manrope-400.woff2") format("woff2"),
       url("../fonts/manrope/manrope-400.woff") format("woff");
}
```

However the generated code lacks the `pathPrefix` resulting in 404s:

```css
@font-face {
  font-display: fallback;
  font-family: "Manrope";
  font-style: normal;
  font-weight: 400;
  src: url("/assets/fonts/manrope/manrope-400.woff2") format("woff2"),
       url("/assets/fonts/manrope/manrope-400.woff") format("woff");
}
```

Not sure what the best way is to address this. For the time being I’m manually updating the paths in the generated files but would love to find a more automated solution.

### Reproduction steps

1. Create boilerplate Eleventy site
2. Add [HTML base plugin](https://www.11ty.dev/docs/plugins/html-base/)
3. Set `pathPrefix` to anything
4. Add a CSS file and include a webfont using `@font-face`
5. Build the site
6. Check the font path in the generated CSS

### Expected behavior

I’d love to find a way to auto update all URLs in CSS files. At the very least, I think it would be helpful to add a note about this in the HTML base docs.

Thanks!
