### ISSUE TITLE
How can I set a page title from paginated pages? Front Matter cannot access data

### ISSUE THREAD

**Issue by therealpecus** [11ty/eleventy#315]
I have a template configured to output multiple pages via pagination. The paginated collection contains a reference for each item that I would like to use to set the page title, but I can't find a way to pass it to the template.
```
---
layout: layouts/skeleton.njk
pagination:
  data: archives.posts
  size: 1
  alias: item
permalink: archive/{{ item.slug }}/index.html
title: Blog post archive for {{ item.month }} - {{ item.year }}
---
```

while `item.slug` is available in the `permalink` special variable, it is not exposed to a generic variable as `title`

skeleton.njk would of course contain
```
<title>{{ title }}</title>
```

This is primarily for SEO reasons: having a coherent H1 and title tag helps, but I can think of several other cases where data in Front Matter might be useful.

**UPDATE**
As a workaround, aliasing all paginated content to the same identifier (e.g. `item`) and explicitely providing a title via an inner property (e.g. `item.title`) allows to use a logic fallback on the skeleton template:
```
<title>{{ title or item.title }}</title>
```
I would still prefer a more streamlined approach, but my case might be an edge one (I am sourcing all content from elsewhere).
