### ISSUE TITLE
Markdown blockquotes get wrapped in a <p> tag

### ISSUE THREAD

**Issue by Obspogon** [11ty/eleventy#3607]
### Operating system

Windows 10

### Eleventy

3

### Describe the bug

When I use blockquotes in markdown files, they get wrapped in `p` tags. This:

`> Some Quote`

becomes this:

`<blockquote><p>Some Quote</p></blockquote>`

when i want this:

`<blockquote>Some Quote</blockquote>`

because otherwise, the `p` tag adds an ugly amount of padding.

**Comment by Ryuno-Ki** [comment]
That's by design of markdown-it: https://markdown-it.github.io/ (switch to `source` tab in the right pane).

See https://github.com/markdown-it/markdown-it/issues/503

**Comment by Obspogon** [comment]
OK, i've worked around it with CSS. However, I noticed that some whitespace is inserted between the `p` block and the `::before` and `::after` elements, as pictured below. This adds an extra space between the quote characters and the paragraph.

![image](https://github.com/user-attachments/assets/f138b3fd-52e1-4ccf-b7d5-a337b1c07737)

This is what I set those values to:

```css
blockquote::before {
	content: "“";
}
blockquote::after {
	content: "”";
}
```

Is there a way to not generate those extra whitespaces when using `::before` and `::after`?

**Comment by Ryuno-Ki** [comment]
Would help if you could share a link if it is deployed somewhere :smile_cat: 

> Is there a way to not generate those extra whitespaces when using `::before` and `::after`?

```css
blockquote::before,
blockquote::after {
	display: none;
}
```

should do the trick.

**Comment by Obspogon** [comment]
That also hides the `“` and `”` along with the whitespace.

**Comment by Obspogon** [comment]
I should probably mention how my blockquotes css is set up.
```css
blockquote {
	border-left: var(--border);
	padding: 1em;
	font-style: italic;
	margin: 1em auto;
}
blockquote > p {
	display: inline;
	white-space: pre-line;
}
```

**Comment by Obspogon** [comment]
SOLVED! I just had to apply the quotes/pseudo-classes to the `p` inside the `blockqoute`.

```css
blockquote > p::before {
	content: "“";
}
blockquote > p::after {
	content: "”";
}
```
