### ISSUE TITLE
Partial uses collection, which include partials - js/css includes in nested partials aren't loading

### ISSUE THREAD

**Issue by jasonday** [11ty/eleventy#3730]
### Operating system

Windows

### Eleventy

3.0.0

### Describe the bug

I have a collection called docs. Docs get rendered in a details partial on a page. 
```
{% set itemList = collections.docs %}
{% include 'partials/details.njk' %}
```
I also have a gallery partial, which takes frontmatter and builds a gallery:
```
gallery:
  - image: /assets/images/projects/FAR/FAR1-workbook.PNG
    alt: 'Fidelity Investments FAR workbook, 1st page'
    caption: 'Fidelity Accessibility Requirements scoring workbook'
  - image: /assets/images/projects/FAR/FAR1-scores-for-steps.PNG
    alt: 'Close-up of a delicate white flower with a yellow center, surrounded by green leaves'
    caption: 'Jasmine nightshades blooming in July'
  - image: /assets/images/projects/FAR/FAR1-worksheet.PNG
    alt: "A traditional Asturian village with it's raised granaries, surrounded by lush green hills and mountains"
    caption: 'Traditional houses in Santullano, Somiedo Natural Park, Asturias'
  - image: /assets/images/projects/FAR/FAR1-worksheet-filled.PNG
    alt: 'Close-up with unfocused background of a vibrant large blue butterfly gracefully perched on a delicate flower amidst lush green grass'
    caption: 'A large blue (Phengaris arion)'
---
```
and the include
```
{% include "partials/gallery.njk" %}
```

If I use the gallery include within the docs collection, the gallery include's css/script includes are not loaded. 

How do I ensure that nested nature of the includes, works as expected?
