### ISSUE TITLE
Regression. eleventyComputed is not merged/executed in the DataCascade

### ISSUE THREAD

**Issue by KajKandler** [11ty/eleventy#3831]
I make use of the eleventyComputed in two places in the data cascade.

In a folder-level data file, I calculate

```
export default {
    // Optional - in a global data file or config
    layout: "layouts/glossary.njk",
    tags: ["glossary"],
    eleventyComputed: {
        first_letter: function (data) { return data.title[0] }
    }
};
```

In the YAML front matter of the template, I calculate
```
eleventyComputed:
  "id": "{{ metadata.url }}glossary/entity/#webpage"
```
The later does not get computed, but stays `"{{ metadata.url }}glossary/entity/#webpage"`, where I'd expect `"https:my.example.com/glossary/entity/#webpage"`

After resetting to 11ty 3.0.0 the behavior works just as expected.

**Comment by zachleat** [comment]
Can you include a minimum viable test case for reproduction? I created one myself but it didn’t exhibit the behavior you described

**Comment by adamstddrd** [comment]
I'm running into this same issue. I have some template front matter that looks like this:
```
eleventyComputed:
  downloads:
  -
    title: "Steady for desktop"
    description: "A fast, focused Steady experience, complete with native notifications."
    links:
    -
      title: "MacOS"
      url: "{{ site.download_link_mac }}"
      button: "Download"
      icon: "icon-apple"
    -
      title: "Windows"
      url: "{{ site.download_link_windows }}"
      button: "Download"
      icon: "icon-windows"
(truncated for brevity)
```

In 11ty 3.1, values like `{{ site.download_link_mac }}` are present in the rendered output. When I downgrade to 11ty 3.0, the values are computed as expected.
