### ISSUE TITLE
Regression in v3.1.0: Template strings in Arrays in Computed Data not rendering

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy#3850]
Regression introduced in v3.1.0 from #3728.

[Release notes](https://github.com/11ty/eleventy/releases/tag/v3.1.0) on the original fix:

> Fixes for bugs with merging Arrays in eleventyComputed. Arrays are now treated as a single entity when merging over non-computed data. Arrays will still be merged in the data cascade from multiple eleventyComputed entries. https://github.com/11ty/eleventy/issues/3728

```
eleventyComputed:
  downloads:
  -
    title: "Steady for desktop"
    description: "A fast, focused Steady experience, complete with native notifications."
    links:
    -
      title: "MacOS"
      url: "{{ site.download_link_mac }}"
      button: "Download"
      icon: "icon-apple"
    -
      title: "Windows"
      url: "{{ site.download_link_windows }}"
      button: "Download"
      icon: "icon-windows"
(truncated for brevity)
```

originally via @adamstddrd here: https://github.com/11ty/eleventy/issues/3831#issuecomment-2936751971
