### ISSUE TITLE
Find post by slug

### ISSUE THREAD

**Issue by robdodson** [11ty/eleventy#399]
Heyo 👋

I tried looking through the issue tracker and didn't turn up anything that quite matched what I'm trying to do. Apologies if this has been answered before...

I'm creating a table of contents page, and using the slug for each post as an identifier. I have my YAML organized like so:

```yaml
---
layout: path
topics:
- title: Understand the diverse needs of users
  guides:
    - what-is-accessibility
- title: Make your site keyboard accessible
  guides:
    - keyboard-access
    - use-semantic-html
    - control-focus-with-tabindex
    - style-focus
- title: Understand semantics and basic screen reader support
  guides:
    - semantics-and-screen-readers
    - headings-and-landmarks
    - labels-and-text-alternatives
---
```

I'd like to be able to use the slug of each guide to find its data object and pull out its `title` property. That would let me do something like this:

```html
<!-- GUIDES FOR TOPIC  -->
<ul class="guides">
  {% for slug in topic.guides %}
  <li>
    <a href="./{{slug}}">
      // somehow access the YAML for the guide that lives
      // at `slug` so I can display guide.title
    </a>
  </li>
  {% endfor %}
</ul>
```

Is my best bet to just write a shortcode to lookup the posts and use `readFileSync` to grab their contents and parse their YAML?

Another alternative I thought of was to have all of the posts be in a collection, and filter the collection by slug until I find the right object. But that felt a little weird to me because I have to remember to add each post to this collection, even though I already have a unique identifier that I could use to look them up.
