### ISSUE TITLE
Cannot paginate `collections.all` in v0.8.0

### ISSUE THREAD

**Issue by johnridesabike** [11ty/eleventy#477]
Since installing v0.8.0, I’m unable to paginate `collections.all`. 

My template front matter: 

```yaml
pagination:
    data: collections.all
    size: 10
    alias: pages
    reverse: true
```

The debug output error:
```
Eleventy:EleventyErrorHandler Problem writing Eleventy templates: +4m
  Eleventy:EleventyErrorHandler Dependency Cycle Found: ___TAG___all -> ./archive.njk -> ___TAG___all (Error): +96ms
  Eleventy:EleventyErrorHandler (error stack): Error: Dependency Cycle Found: ___TAG___all -> ./archive.njk -> ___TAG___al
```

Paginating other tags (e.g. `collections.myTag`) works fine.
