### ISSUE TITLE
Nesting front matter data

### ISSUE THREAD

**Issue by pdkaizer** [11ty/eleventy#534]
Is it possible to nest front matter data?

**Comment by Ryuno-Ki** [comment]
What do you mean? (I can imagine different things)
Could you provide some examples?

**Comment by pdkaizer** [comment]
For example in Jekyll I can have:
---
portfolio-items:
- title: Medicaid.gov
   image: Medicaid-2018-600.png
   text: Design and front-end dev lead on a Medicaid project establishing a design system for their 2 primary websites that will be based on the US Web Design Standards.
   skills: Website design, Sketch, front-end development
   role: Design and front-end dev lead
   url: https://www.medicaid.gov/
   filter: Website

- title: SAMHSA Knowledge Network
   image: SAMHSA-KN-600.png
   text: User Experience lead on the resource library website for the Substance Abuse and Mental Health Administration.
   skills: Wire framing, UX design
   role: User Experience Lead
   url: https://knowledge.samhsa.gov/
   filter: Website
---

And then loop through and output with:
		{% for portfolio-item in page.portfolio-items %}
		<div class="portfolio-section clearfix">
			<section class="portfolio-image">
				<img src="/images/portfolio/{{portfolio-item.image}}" alt="" class="img-responsive" />
			</section>

			<section class="portfolio-text">
				<h2>{{portfolio-item.title}}</h2>
				{{portfolio-item.text}}

				<p><strong>Type:</strong> {{portfolio-item.filter}}</p>
				<p><strong>Skills:</strong> {{portfolio-item.skills}}</p>
				<p><strong>Role:</strong> {{portfolio-item.role}}</p>
				<p><strong>Visit site:</strong> <a href="{{portfolio-item.url}}">{{portfolio-item.url}}</a></p>
			</section>
		</div>
		{% endfor %}

How would I do the same thin in 11ty?

**Comment by pdkaizer** [comment]
Basically, I want to have an array of data in the front matter and then loop through and output it.

**Comment by edwardhorsford** [comment]
@pdkaizer  Yes that's totally possible. Presuming you're using YAML for your [front matter](https://www.11ty.io/docs/data-frontmatter/), you want something like:

```yaml
portfolio items:
- title: Medicaid.gov
  image: Medicaid-2018-600.png
  text: Design and front-end dev lead on a Medicaid project 	establishing a design system for their 2 primary websites that will be based on the US Web Design Standards.
  skills: Website design, Sketch, front-end development
  role: Design and front-end dev lead
  url: https://www.medicaid.gov/
  filter: Website
- title: SAMHSA Knowledge Network
	image: SAMHSA-KN-600.png
	text: User Experience lead on the resource library website for the Substance Abuse and Mental Health Administration.
	skills: Wire framing, UX design
	role: User Experience Lead
	url: https://knowledge.samhsa.gov/
	filter: Website
```
