### ISSUE TITLE
Feature request: ability to exclude items from pagination

### ISSUE THREAD

**Issue by edwardhorsford** [11ty/eleventy#558]
I use pagination for all sorts of things - tag pages, etc.

I occasionally want to be able to exclude a few items from being paginated - right now I define an entirely new collection that's the same as the previous, but without these items - this feels wasteful, and puts the logic outside of the template.

Easier would be if I could provide a tester function (or similar) that can be run against each item - if it passes, that item doesn't get paginated.

### My use case:

I've got lots of tag pages ~500 or so.

For my more interesting tags I'd like to do bespoke pages with entirely different templates than normal. As these would share the same permalink, I need to _not_ generate those pages with the tags pagination template. Right now I'd need to generate _another_ collection that filters out my 'special' tags. `tagsWithoutSpecial` or similar. 

However this generates a collection I don't really need and won't use elsewhere - it's the logic of the paginated template that I want to alter. 

Something like this would be great:

```yaml
---
{
  pagination: {
    data: 'collections.allTags',
    size: 1,
    alias: 'tag',
    addAllPagesToCollections: true,
    excludeFromPagination: (tag in ['foo', 'bar'])
},
  layout: 'content-page.njk',
}
---
```
