### ISSUE TITLE
Custom Taxonomy pagination/filtering

### ISSUE THREAD

**Issue by dirtystylus** [11ty/eleventy#733]
This is related to #553 

I’ve been attempting to create a custom taxonomy with Eleventy.

My goals:

* Have a separate taxonomy just for a specific collection (aka content type)
* Mimic the behavior of tags: support filtering by that taxonomy, and be able to list all the taxonomy terms

It occurs to me that maybe I’m misunderstanding the mental model of how Eleventy treats collections (I’m not a former Jekyll user), and the way to do this is to still use tags but restrict some tags to a particular collection.

Here’s what I’ve done (my attempt is located at https://github.com/dirtystylus/eleventy-custom-taxonomy):

  
* Created a folder **/projects** with some sample Markdown posts
* Created **projects.json** with a skeleton front matter schema that gets overridden at the post level

```
{
  "layout": "project",
  "content_type": "project",
  "project_types": [
    "interactive"
  ]
}
```

* Created a collection called project

```
eleventyConfig.addCollection("projects", function (collection) {
    return collection.getAll().filter(function (item) {
      return item.data.content_type == "project";
    });
  });
  ```

* Added a filter (using @danfascia’s [gist](https://gist.github.com/danfascia/e15b8e900a767c1b9677d1cbc74cc51c)):

```
eleventyConfig.addFilter("where", function (array, key, value) {
  return array.filter(item => {
    const keys = key.split('.');
    const reduce = keys.reduce((object, key) => {
      return object[key];
    }, item);
    const str = String(reduce);

    return (str.includes(value) ? item : false);
  });
});
```  

* Created **getProjectTypesList.js** to list out the custom taxonomy terms

So far what’s working:

* Project posts are being rendered properly
* Custom taxonomy tags are properly attached to the Project posts
* Listing the taxonomy tags (at `/project-types/`)

What’s not working:

* Filtering by the custom taxonomy tags. 
 
I did find that it *would* filter by a taxonomy term, but only if there was an existing “regular” tag with the same name as the Project taxonomy term. This may have something to do with how I’ve set up **project-types.njk**. I don’t fully understand the different keys that pagination setup uses, so that file looks like this:

```
---
pagination:
  data: collections
  size: 1
  alias: project_type
  filter:
    - all
    - nav
    - post
    - posts
    - tagList
    - projects
    - projectTypesList
  addAllPagesToCollections: true
layout: layouts/home.njk
renderData:
  title: Tagged “{{ project_type }}”
permalink: /project-types/{{ project_type }}/
---
<h1>Tagged “{{ project_type }}”</h1>

{# {% set postslist = projects[ tag ] %} #}
{% set projectslist = collections.projects | where("data.project_types", project_type ) %}
{% include "projectslist.njk" %}

<p>See <a href="{{ '/project-types/' | url }}">all project types</a>.</p>
```
