### ISSUE TITLE
Setting YAML title element programmatically

### ISSUE THREAD

**Issue by LThorburn** [11ty/eleventy#764]
I am generating a bunch of pages from a JSON file, and am trying to set the title for each programmatically, like so:

```
---
pagination:
    data: histograms
    size: 1
    alias: histogram
permalink: /data/{{ histogram.KEY }}/
title: {{ histogram.KEY }}
layout: section-data.njk
---
```

As desired, this seems to attempt to propagate the title back up to my base template where it is inserted in the title element on the page, but instead of the `histogram.KEY` string I get:

```
<title>[object Object]</title>
```

Why does this happen? The programmatic setting of the permalink is working fine.

Thanks in advance for your help.

**Comment by Bagera** [comment]
I think only the permalink is processed in normal frontmatter in 11ty.
There is a special field called "renderData" though and any of its children will be processed.
You would then have to account for this in your title and have it something like this: 
```html
<title>{{ renderData.title or title or metadata.title }}</title>
```

Another solution could be to use javascript frontmatter (requires njk template parsing)
https://www.11ty.io/docs/data-frontmatter/#javascript-front-matter

**Comment by LThorburn** [comment]
Thanks, it does look like others have had success to achieve this using renderData (eg. #470, #255), but I can't get it working at my end. I have:

histogram.njk
```
---
pagination:
  data: histograms
  size: 1
  alias: histogram
layout: section-data.njk
renderData:
  title: {{ histogram.TITLE }}
permalink: /data/{{ histogram.KEY }}/
---

PAGE-SPECIFIC CONTENT HERE.
```

section-data.njk
```
---
title: Data
---

{% extends 'base.njk' %}

{% block content %}
	{{ content | safe }}
{% endblock %}`
```

base.njk
```
<title>{{ renderData.title or title or metadata.title }}</title>

{% block content %}
	Default content.
{% endblock %}
```

and I still get `<title>[object Object]</title>` in the output.

I also had a play with javascript front matter but wasn't able to figure out how to give it access to the `histograms.json` global data file.
