### ISSUE TITLE
Accessing global data in eleventyConfig.addCollection

### ISSUE THREAD

**Issue by tschofen** [11ty/eleventy#775]
I'm trying to create arbitrary pages from a complex global data file. I've been playing with 'addCollection' and am able to create pages. However, I can't figure out how to pass in the global data object into the addCollection method.

Here's what my util function looks like. As you can see the data to extract is currently hard-coded in the util.

```const getComments = (collection, data) => {
  let results = []
  data.forEach((item) => {
    item.comments.forEach(comment => {
      results.push(comment)
    })
  });

  return results
}

exports.getNestedData = collection => {
  return getComments(collection, [
    {name: 'one', comments: ['one', 'two', 'three']},
    {name: 'eins', comments: ['eins', 'zwei', 'drei']}
  ]);
}
```

Relevant code in eleventy.js:
```
eleventyConfig.addCollection("getNestedData", require("./_utils/nested").getNestedData);
```

And finally pulling it into the page: Orders is the name of the global data file.
```
---
layout: layouts/main
title: Orders
permalink: /index-{{ pagination.pageNumber }}.html
postAction: search-results.html
pagination:
  data: collections.getNestedData orders
  size: 1
  alias: order
---
Pagination: {{pagination}}
```

Any idea how I can pass in the global data, or if need be access the global data file from within the getNestedData function?

Thanks in advance.
