### ISSUE TITLE
List of posts by author 

### ISSUE THREAD

**Issue by onebitrocket** [11ty/eleventy#888]
Hi, 

How can I generate a list of blog posts filtered by author data?

This is my set up so far...

My project is based on eleventy-base-blog and I’m using netlify-cms to create an authors collection. Netlify-cms outputs each author as markdown files in an authors folder. 

in the authors folder there is an authors.json file that updates the permalink to `/blog/authors/{{ author.title | slug }}`

In my config the author collection is set as a folder field type so I can call the authors collection in a relational field in my blog posts. 

I’m a little stuck. Any advice would be greatly appreciated. 

Thanks

**Comment by pdehaan** [comment]
Probably not the best solution (and I've haven't tried netlify-cms yet), but I managed to fake a blog+author archive at https://github.com/pdehaan/11ty-blog-authors/blob/master/src/_11ty/collections.js

Basically it just fetches all blog posts in my ./src/blog/ folder, and does an `Array#reduce()` to do a map of `{"Author Name": [Array of post data]}` style object.

1. [`"/authors/"` template](https://github.com/pdehaan/11ty-blog-authors/blob/master/src/author-index.njk)
2. [`"/authors/{{ name | slug }}/"` template](https://github.com/pdehaan/11ty-blog-authors/blob/master/src/author-archives.njk)

**Comment by onebitrocket** [comment]
@pdehaan Thanks for this - really really helpful!

I got his to working perfectly. I can see how this can be extended for additional relational content.

I've also got this working in combination with netlify cms

This is the collection I set up in my netlify cms config.yml file
``` yml
- name: "blogauthors"
    label: "Blog authors"
    label_singular: "Blog author"
    description: "All the blog authors"
    folder: 
    create: true 
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Job Title", name: "jobTitle", widget: "string", required: false }
```
The above writes markdown files stored above folder.
_I have to remove the slug (`slug: "{{ slug }}"`) option from the collection settings as it was writing `.md` rather than `name.md`_

Then in a corresponding collection for blog posts I assign the author field using a relation widget that reads the above `blogauthor` collection

``` yml
  - name: "blog"
    label: "Blog posts"
    label_singular: "Blog post"
    description: "All the blog posts"
    folder: "_src/blog" 
    create: true
    slug: "{{ slug }}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"], required: false }
      - { label: "Featured Image", name: "featuredImage", widget: "image", required: false }
      - { label: "Author", name: "author", widget: "relation", collection: "blogauthors", searchFields: "title", valueField: "title", displayFields: "title" }
      - { label: "Body", name: "body", widget: "markdown" }
```
